### ISSUE TITLE
Creating own pallete

### ISSUE THREAD

**Issue by fjenik** [root-project/jsroot#124]
Hello,
How can i create my own pallete in JSROOT? I want to create my own pallete for this examlpe in root js.

> https://root.cern/js/latest/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=COLZ

**Comment by linev** [comment]
Hi,

There are two methods to select color palette.

First is to change global palette id `&palette=101`

https://root.cern/js/latest/?nobrowser&palette=101&file=../files/hsimple.root&item=hpxpy;1&opt=COLZ
 
This change default 57 palette for all consequent drawings.

Or use palette id in draw options `&opt=COLZ_pal101`

https://root.cern/js/latest/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=COLZ_pal101

There is no direct way to add user-defined palette.
The only possibility will be to provide your own implementation of JSROOT.Painter.GetColorPalette function. See;

https://github.com/linev/jsroot/blob/master/scripts/JSRootPainter.more.js#L100

Regards,
Sergey

**Comment by linev** [comment]
Hi,

Does it solve your problem?
Actually, there few other methods to change colors in JSROOT.
For instance, one just can exchange color table completely.

Sergey

**Comment by fjenik** [comment]
Yes, thank you for fast answer
