### ISSUE TITLE
How to set/update axis titles for histograms, mutigraphs

### ISSUE THREAD

**Issue by mazurov** [root-project/jsroot#126]
Hi,

You  have a nice example of drawing multigraph. Is it possible to set axis titles in histograms or multigraphs from javascrtipt?

https://root.cern/js/latest/api.htm#custom_html_tmultigraph
https://root.cern/js/latest/api.htm#custom_html_tmultigraph_src

**Comment by linev** [comment]
Hi,

I have very similar example:

https://root.cern/js/latest/demo/multigraph_legend.htm

It shows how extra histogram can be created for the axis drawing.
If you don't want custom axis labels, use following code:

         var h1 = JSROOT.CreateTH1(20);
         h1.fName = "axis_draw";
         h1.fTitle = mgraph.fTitle;
         h1.fXaxis.fTitle = "xaxis";
         h1.fYaxis.fTitle = "yaxis";
         h1.fYaxis.fXmin = 0;
         h1.fYaxis.fXmax = Math.max(graph1.fY[npoints-1], graph2.fY[npoints-1]);
         mgraph.fHistogram = h1;


Regards,
Sergey

**Comment by mazurov** [comment]
OK. Thank you. I will try.

P.S. This example is not in the github repository?

**Comment by linev** [comment]
> This example is not in the github repository?

Not yet.

**Comment by linev** [comment]
Hi,

I add example to repository (first to dev branch). 
You can see it also here:

http://jsroot.gsi.de/dev/api.htm#custom_html_tlegend

It is not only custom axis title or TLegend labels.
I also implement correct update of all these objects.

Code only in dev version - some weeks later will be available as JSROOT 5.2

Regards,
Sergey
