### ISSUE TITLE
simpleGUI - impossible to set width/size?

### ISSUE THREAD

**Issue by andrmor** [root-project/jsroot#128]
Is it possible in some way to control width/height and position of the simpleGUI div?
I am using
<div id="simpleGUI" browser=no file="testGeom.root" item="aaaa" opt="rotate&transp90&all" > ...
 and the geometry is shown on top of other content of the page, ignoring any width/heights constrains.
I did not find any other way to show my local files on our project webpage without installing the JSROOT, can some basic controls be provided please?

**Comment by linev** [comment]
To show you code you can use jsfiddle as in this example:

https://jsfiddle.net/Ls5nvtfw/

**Comment by linev** [comment]
With jsfiddle is not easy to use "?gui" option, required for simpleGUI

Here is example:

https://jsfiddle.net/n4je00o3/1/

When you specify geometry for simpleGUI div, you should use style like this:

     style="width:400px;height:300px;position:relative"

Here position:relative is important.

**Comment by andrmor** [comment]
Thank you very much! Sorry if it was too "childish" question :)

**Comment by linev** [comment]
> Thank you very much! Sorry if it was too "childish" question :)

Actually it is not so obvious.
Normally complete browser window is used and geometry just ignored. 
If one wants to specify custom geometry for simpleGUI, one should use position which is not 'static'.
