### ISSUE TITLE
Drawing multiple objects on the same div

### ISSUE THREAD

**Issue by JustOneJJ** [root-project/jsroot#129]
Hi,
When drawing multiple histograms on the same div canvas don't adjust its size so sometimes top part of histogram gets cut off. 

Currently I'm iterating over a list of JSON objects and calling JSROOT.draw function for each. Is there some way to adjust canvas size according to the largest histogram?
![image](https://cloud.githubusercontent.com/assets/11797743/24917854/c066b6b4-1ede-11e7-988d-f51df1fe5001.png)

**Comment by linev** [comment]
Hi,

You have two alternatives - set min/max for the first histogram:
    
     hist1.fMinimum = 0;
     hist2.fMaximum = 0;

Or create THStack and set min/max for THStack object. 
Example on how THStack can be created:

https://root.cern/js/latest/api.htm#custom_html_thstack
https://github.com/root-project/jsroot/blob/master/demo/thstack.htm

Both methods more or less equivalent.

**Comment by linev** [comment]
Small update - with THStack you can keep default min/max values
JSROOT automatically adjust Y range to maximum from all histograms

**Comment by JustOneJJ** [comment]
THStack works perfectly.

Thank you.

**Comment by linev** [comment]
As I can see, you are using Latex in the labels.
You can try to enable MathJax for text rendering.
Either add "&mathjax" into URL or in the code you can write:

    JSROOT.gStyle.MathJax = 1;

**Comment by JustOneJJ** [comment]
MathJax gives much better rendering.
Thank you for advice.
