### ISSUE TITLE
Cannot plot two TGraphs on same canvas: expected behaviour?

### ISSUE THREAD

**Issue by nasfarley88** [root-project/jsroot#130]
I am plotting two TGraphs on a single canvas with `JSROOT.draw(pad, tgraph, "same")`.

Should this work? Or is this undefined behaviour?

**Comment by linev** [comment]
Hi,

Potentially yes, but you should use call-back routines.
You cannot simply perform two subsequent calls:

     JSROOT.draw(padid, tgraph1, "").
     JSROOT.draw(padid, tgraph2, "same").

I recommend to use TMultiGraph, as shown here:

https://root.cern/js/latest/api.htm#custom_html_tmultigraph_src

If you have already graph objects, just do:

    var mgraph = JSROOT.CreateTMultiGraph(graph1, graph2);
    mgraph.fTitle = "Drawing " + cnt++;
    JSROOT.draw('object_draw', mgraph);

Regards,
Sergey

**Comment by nasfarley88** [comment]
Great, this looks ideal. 

Will `CreateTMultiGraph` use the formatting from the existing graphs? Or use the defaults?

**Comment by linev** [comment]
> Will CreateTMultiGraph use the formatting from the existing graphs? Or use the defaults?

Without extra configurations TMultiGraph just drawing first graph and then second graph.

**Comment by nasfarley88** [comment]
Good, I'll use `CreateTMultiGraph` instead then.
