### ISSUE TITLE
Drawing Canvas and histogram ranges

### ISSUE THREAD

**Issue by DanielWielanek** [root-project/jsroot#131]
Hi,
I have problem with drawing histograms. I would like to draw TCanvas however it seems to be "cutted off". In attachement example of problem - this histogram should be from -1 to 1 bu it's up to 0.8 ("bar with colors" hide part of histogram).
[tpc_cal.zip](https://github.com/root-project/jsroot/files/1093894/tpc_cal.zip)

**Comment by linev** [comment]
Hi Daniel,

You are using older JSROOT version 4.8.
With current code (JSROOT 5.2) I get following result:

![screenshot](https://user-images.githubusercontent.com/4936580/27472733-cc47e7da-57fc-11e7-9692-c6e2f8c7c802.png)

It is still not absolutely perfect, but histogram range displayed correctly.

Regards,
Sergez
