### ISSUE TITLE
OptFit

### ISSUE THREAD

**Issue by f9daq** [root-project/jsroot#134]
I would like to display the fit box in the histogram. 
What you suggested in https://github.com/root-project/jsroot/issues/42 - adding  
`JSROOT.gStyle.OptFit = 1111; `
does not work. I appended the example.
Thanks
[drawhist.txt](https://github.com/root-project/jsroot/files/1250878/drawhist.txt)

**Comment by linev** [comment]
Hi,

In jsroot version 5 JSROOT.gStyle is instance of TStyle object.
Therefore one should specify:

     JSROOT.gStyle.fOptFit = 1111;

Regards,
Sergey
