### ISSUE TITLE
Trouble with CORS requests to THttpServer

### ISSUE THREAD

**Issue by gauzinge** [root-project/jsroot#135]
Hi, I am having a fair bit of trouble with displaying objects and files from a THttp Server. I am writing a web application as a GUI for a DAQ framework. The backend is c++ based and creates pages via cgicc. My main GUI has an instance of THttpServer running and registers objects as they are created. This works fine when accessing the THttpServer in a separate browser tab. However, when I want to embed my plots in the web app, the THttpServer refuses any XMLHttpRequests sent via JSROOT (origin my server:myport is not allowed by Access-Control-Allow-Origin - both are running on the same machine but on different ports). I have tried to add the cors option in the THttpServer constructor as per https://root.cern.ch/doc/master/classTHttpServer.html but when I use a string like "http:8080s?cors" the server is not reachable and if I put "http:8080?cors" it has no effect. For what it's worth, I am on root v5.34 on SLC6.

I have even tried to just add a root file to the server via server->AddLocation() and implemented the simpleGUI div in my page and use the url of the added file in the simpleGUI div as files="" argument - with the same result that the request from my app is blocked by THttpServer. The file is there and served by the server as I can download it under the URL...

I have read through the User guide of THttpServer and JSROOT (+ the examples) about 5 times now and I can not figure out a solution to this. Essentially, I would like to embed a simpleGUI that allows to browse all files in a directory + whatever objects the THttpServer has registered - is there a recommended way to do this or am I missing something really important here?

Thanks a lot
Georg

**Comment by linev** [comment]
Hi Georg,

> For what it's worth, I am on root v5.34 on SLC6.

This is main problem. Support of CORS header provided only with actual ROOT6 version.
ROOT5 version of THttpServer is not updated since ~6 months.

Can you switch to ROOT6? 

Regards,
Sergey

**Comment by gauzinge** [comment]
I can that that as an immediate workaround if there is no way to get this working properly with root 5.34

**Comment by linev** [comment]
>  if there is no way to get this working properly with root 5.34

CORS support is relatively simple to back-port to ROOT5.
But there are many other small and big changes, especially in JSROOT itself.
For the moment decision is made that ROOT5 is no longer updated 
and I need very good arguments (not only for myself) to apply changes for ROOT5.

If you compile ROOT5 yourself, you could patch it. 
Just add at very end of THttpServer::ProcessRequest following code:

     arg->AddHeader("Access-Control-Allow-Origin", "*");

Probably, it will solve your problem.

Regards,
Sergey

**Comment by gauzinge** [comment]
I am giving root from /afs a shot for the time being. could you let me know which version exactly supports CORS? I can easily get 6.05

**Comment by linev** [comment]
>  I can easily get 6.05

Only starting from ROOT 6.10 CORS header is supported.

**Comment by gauzinge** [comment]
thanks, I'll try with a more recent root version on CC7
