### ISSUE TITLE
JSROOT stopped working

### ISSUE THREAD

**Issue by DanielWielanek** [root-project/jsroot#136]
Hi, sorry for stupid question but JsROOT stopped working when I downloaded newer JSROOT.
I use following code to "display" TCanvas in root file:
` <meta charset="UTF-8">  
<html>
<head>
<link rel="stylesheet" href="../../../table.css" type="text/css"/>
<script src="../../../nica_js/scripts/JSRootCore.js?2d&onload=startGUI" type="text/javascript"></script>
</head>
<body>
<script type='text/javascript'>
var filename = "cutmon.root";
 JSROOT.OpenFile(filename, function(file) {
 JSROOT.gStyle.Palette= 50;
file.ReadObject("cutmon;1", function(obj) {
JSROOT.draw("drawing", obj, "colz");
;});
;});
</script>
<div id="drawing" style="width:90%; height:900px"></div>
</body></html>`
an hints how can I get my beautiful plots again?

**Comment by linev** [comment]
Hi Daniel,

Did you check developer console in the web browser?
Are there any errors? 

Code itself looks ok and should work - it is very similar to our basic examples:

https://root.cern/js/latest/api.htm#custom_html_read_root_file_src
https://root.cern/js/latest/api.htm#custom_html_read_root_file

Probably, you could remove extra URL parameters for JSRootCore.js script - 
they are no longer required for such basic functionality.

Regards,
Sergey

**Comment by DanielWielanek** [comment]
Hi,
I found reason. Some of JsROOT files where not copied, therefore JsROOT didn't work. After copying them it seems work.
Sorry for trouble.
