### ISSUE TITLE
strict mode + old Firefox

### ISSUE THREAD

**Issue by sekrasoft** [root-project/jsroot#137]
I downloaded and unpacked provided packages as recommended.

It workes well in the latest Firefox but it doesnt't work in Firefox 45. Firefox console contained the following error messages:
```
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function JSRootIOEvolution.js:1517:21
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function JSRootPainter.js:4665:18
Error: JSROOT.Painter not defined
 JSRootPainter.hierarchy.js:19:1
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function JSRootPainter.jquery.js:694:21
```
[UI via rawgit.com](http://rawgit.com/root-project/jsroot/master/index.htm?path=http://jsroot.gsi.de/files/) shows similar behavior in old Firefox'es but https://root.cern/js/5.3.1/ works well. The difference I found is that the first one uses `JSRootCore.js` and the second one uses `JSRootCore.min.js`.

Switching to the minified version in index.htm helps to avoid errors in old Firefox.

**Comment by linev** [comment]
Hi,

Strange observation.
Seems to be, during "minification" "use strict" directive is removed.
I introduce it to keep under control most obvious bugs in the source code.

Regards,
Sergey
