### ISSUE TITLE
"HIST" option ignored when drawing Histograms

### ISSUE THREAD

**Issue by vargasa** [root-project/jsroot#139]
It looks like the option `HIST` is being ignored as the plot for a TH1I histogram in TBrowser is different from the one that I see on-line using jsroot. The following script creates a TFile so you can see the problem

```
{
  TFile *f = new TFile("HIST.root","RECREATE");
  
  Int_t x[4] = {1,2,3,4};
  Int_t y[4] = {5,6,7,8};

  TH1I *h1 = new TH1I("h1","h1",5,0,5);

  for (Int_t i =0; i < 4; i++){
    h1->Fill(x[i],y[i]);
  }
  h1->SetFillColor(1);
  h1->SetOption("HIST");
  h1->Draw();
  h1->Write("h1");
  f->Close();
}
```

**Comment by linev** [comment]
Hi,

Which version you are using.
If I save canvas in the file, with latest JSROOT version I got:

http://jsroot.gsi.de/latest/?file=../files/tmp/c1.root&item=c1

Same result I obtain if directly draw histogram from the canvas list of primitives:

http://jsroot.gsi.de/latest/?file=../files/tmp/c1.root&item=c1/h1

Regards,
Sergey

**Comment by vargasa** [comment]
Hi @linev. I'm using the latest version but I simplified the script because I was using `THStack`

Try this :
```
{
  TFile *f = new TFile("HIST.root","RECREATE");
  
  Int_t x[4] = {1,2,3,4};
  Int_t y[4] = {5,6,7,8};
  Int_t y2[4] = {4,4,5,4};

  TH1I *h1 = new TH1I("h1","h1",5,0,5);
  TH1I *h2 = new TH1I("h2","h2",5,0,5);
  THStack *hs = new THStack();

  for (Int_t i =0; i < 4; i++){
    h1->Fill(x[i],y[i]);
    h2->Fill(x[i],y2[i]);
  }
  h1->SetFillColor(1);
  h2->SetFillColor(2);
  hs->Add(h1,"HIST");
  hs->Add(h2,"HIST");
  hs->Draw();
  hs->Write("hs");
  f->Close();
}
```

**Comment by linev** [comment]
Hi,

Now I see. You need to specify "nostack" option to get result as ROOT produce with default draw option:

http://jsroot.gsi.de/latest/?file=../files/tmp/stack.root&item=hs&opt=nostack

Probably "nostack" should always be default option - I will check how ROOT handle this.

Regards,
Sergey

**Comment by linev** [comment]
Hi again,

Finally I found and fix a problem.
When no any draw options for THStack was specified, "E" draw option was used for histograms.
It is not correct and now looks different:

http://jsroot.gsi.de/dev/?file=../files/tmp/stack.root&item=hs

This patch will appear soon as JSROOT 5.3.4.
Thanks for reporting the problem!

Regards,
Sergey

**Comment by vargasa** [comment]
My pleasure. Thank you @linev
