### ISSUE TITLE
Central line not drawn when using TGraphErrors "A3C" Option

### ISSUE THREAD

**Issue by vargasa** [root-project/jsroot#140]
The central line is not drawn when using "a3c" TGraphErrors option, please see the difference between the output of JSROOT and Interpreted version of the following ROOTFile:

```
{
  TFile *f = new TFile("TestErrors.root","RECREATE");
  Float_t x[5] = { 1., 2., 3., 4., 5.};
  Float_t y[5] = { 1., 2., 3., 4., 5.};
  Float_t dx[5] = { 0.5, 0.5, 0.5, 0.5, 0.5};
  Float_t dy[5] = { .1, .2, .1, .2, .5};

  TCanvas *c1 = new TCanvas();
  TGraphErrors *g1 = new TGraphErrors(5,x,y,dx,dy);
  g1->SetFillColor(4);
  g1->SetFillStyle(3003);
  g1->Draw("A3C");
  c1->Write("cc");
  
  f->Close();
}
```

**Comment by linev** [comment]
Hi,

Central line (letter "C" from "A3C") simply not implemented in JSROOT.
I will provide it - thanks for reporting the problem.

Supported list of draw options you can find here:

https://root.cern/js/latest/examples.htm

Regards,
Sergey

**Comment by vargasa** [comment]
Thank you @linev. I also tried "a3l" which is implemented but it is not showing up if I add the band, there is no problem with "AL" though. Also, is it possible to get a "JSROOT" Category in the root-forum. Perhaps @Axel-Naumann  could help us with that?

**Comment by bellenot** [comment]
@vargasa no need to create a new category, you can already use the 'jsroot' tag

**Comment by linev** [comment]
Hi,

Now "C" and "L" options can be combined with other draw options:

   http://jsroot.gsi.de/dev/?file=../files/graph.root&item=c41/Graph&opt=a4c
   http://jsroot.gsi.de/dev/examples.htm?more#tgraph_macro2

@couet 
Can you check drawing of last canvas with native ROOT?

     [shell] root -l https://root.cern/js/files/macro2.root                                                                                                                                                                       
     root [1] c1->Draw()

ROOT does not show "L" drawing for the first TGraph - fill area hides line drawing completely. 
Probably one should do drawing in other order - first fill area and then line (as JSROOT does it now).

Regards,
Sergey

**Comment by couet** [comment]
Yes the line is hidden I guess you should change the drawing order

**Comment by linev** [comment]
Just try to make fill attributes semi-transparent 
Line is drawn, but not seen

**Comment by couet** [comment]
Ah yes I see .. in case of "e3al" the line should be drawn last. I will check

**Comment by vargasa** [comment]
That's fine @bellenot. Thanks for addressing this issue @linev
