### ISSUE TITLE
TH2 shifted alphanumeric axis labels

### ISSUE THREAD

**Issue by hcbeck** [root-project/jsroot#141]
Hi, 
I tested alphanumeric axis labels and wanted to have the tixs and the labels centred on the bin. I followed the root example for labels and TH2: https://root.cern.ch/root/html/tutorials/graphs/labels2.C.html
I changed the range of the histogram like so: 
TH2F *h = new TH2F("h2","test",nx,0.5,nx+0.5,ny,0.5,ny+0.5);
I saved the canvas in a root file and looked at it with TBrowser and with the jsroot web site (latest version). In the jsroot display the labels on both axis are shifted in negative direction by half a bin so that the first label is not displayed any more and the labels are not centred. In TBrowser the display is as I expected with all centred labels. 
I tested TH1F with x axis labels and they are fine. 
Could you have a look at this, please?

Thank you and Merry Christmas!
Helge

**Comment by linev** [comment]
Yes, till now labels always were placed on "regular" axis, where x values were identical with label index.

Now should work:

http://jsroot.gsi.de/dev/?file=../files/tmp/labels2.root&item=c1

Thanks for reporting the problem.

**Comment by hcbeck** [comment]
Wow that was quick! Thank you very much!
