### ISSUE TITLE
Histograms with negative BinContent using "HIST" Draw Option

### ISSUE THREAD

**Issue by vargasa** [root-project/jsroot#143]
Hi @linev 

When trying to make a histogram's bar plot using the "HIST" option, the output on ROOT is different from JSROOT output which looks more like the "AB1" option when using TGraph. You can see the difference with this file:

```
{
  TFile *f = new TFile("HIST.root","RECREATE");
  
  Int_t x[4] = {1,2,3,4};
  Int_t y[4] = {5,-2,7,-1};

  TH1I *h1 = new TH1I("h1","h1",5,0,5);

  for (Int_t i =0; i < 4; i++){
    h1->Fill(x[i],y[i]);
  }
  h1->SetFillColor(1);
  h1->SetOption("HIST");
  h1->Draw();
  h1->Write("h1");
  f->Close();
}
```

**Comment by linev** [comment]
Hi,

Yes, you are right. Now should work similar to ROOT:

http://jsroot.gsi.de/dev/examples.htm?more#th1_negfill

Regards,
Sergey

**Comment by vargasa** [comment]
Thanks @linev for addressing this issue. I have a question though, whenever I modify the Xaxis range for that particular histogram the bars are not drawn (if they were not being shown before) until I reach the lower limit of the axis. I think is easier to understand by running a similar code:
```
{
  TFile *f = new TFile("HIST.root","RECREATE");
  
  Int_t x[10] = {1,2,3,4,5,6,7,8,9,10};
  Int_t y[10] = {5,-2,7,-1,10,-3,-4,5,-6,9};

  TH1I *h1 = new TH1I("h1","h1",10,0,11);

  for (Int_t i =0; i < 10; i++){
    h1->Fill(x[i],y[i]);
  }
  h1->SetFillColor(kGreen);
  h1->SetOption("HIST");
  h1->GetXaxis()->SetRangeUser(5,10);
  h1->Draw();
  h1->Write("h1");
  f->Close();
}
```
Loading the file in JSROOT and then scrolling down over the Xaxis and you'll see what I'm talking about. Also, Does JSROOT have a different Color Palette? I see the kGreen there is different. But I'm also color blind ;)

**Comment by linev** [comment]
h1->GetXaxis()->SetRangeUser(5,10);

User range handled slightly different in JSROOT. It remains selected until full unzoom is done. 
In ROOT user range reset immediately after first unzoom. I was focused on this example when implementing user range:

http://jsroot.gsi.de/dev/examples.htm?more#tcanvas_hsum

Here superimposed histograms have different user ranges.

I will try to provide more consistent solution for your relatively simple use-case.

> Does JSROOT have a different Color Palette? I see the kGreen there is different. But I'm also color blind ;)  

JSROOT uses own color palette, which should be very like to default ROOT palette.
kGreen is just "green" HTML color.

**Comment by linev** [comment]
Now histogram with specified user range should work better. Example is:

http://jsroot.gsi.de/dev/?file=../files/histpainter6.root&item=draw_e34

You can compare with latest release:

http://jsroot.gsi.de/latest/?file=../files/histpainter6.root&item=draw_e34

Now when start doing unzoom, one will see histogram content correctly.

**Comment by vargasa** [comment]
It works smoothly now. Thank you! :heart:
