### ISSUE TITLE
Online event display

### ISSUE THREAD

**Issue by DanielWielanek** [root-project/jsroot#144]
Hi,
Is it possible to use JsROOT as online event display? I see that is possible to draw event + detector from file, but I would like to have API that can take event scene from database instead of loading file for each event.

**Comment by linev** [comment]
Hi,

> Is it possible to use JsROOT as online event display? 

In principle - yes. But till now there is no real application, which doing this with JSROOT.
Currently there is new development called **WebEve**, which will provide functionality comparable to 
original **EVE**, but using _THttpServer_ and _JSROOT_ geometry display. Most probably, there will be correspondent presentation on the next CHEP.

> I would like to have API that can take event scene from database instead of loading file for each event

Using THttpServer as interface, one can access any kind of data through different ROOT interfaces - TFile, TSQLServer, .... Or you can implement your own interface - may be directly from JavaScript and without specialized HTTP server.

**Comment by linev** [comment]
Hi @Rfilip 

Yes, there are different options of online histograms display in JSROOT. And original data not necessary must be generated by C++ ROOT. It could be any data histogram or graph-like data.

There are several methods in JSROOT, which can be used to create appropriate JS objects to display such data. For instance [JSROOT.CreateHistogram](https://github.com/root-project/jsroot/blob/master/scripts/JSRootCore.js#L1673) or [JSROOT.CreateTGraph](https://github.com/root-project/jsroot/blob/master/scripts/JSRootCore.js#L1730). And there are several examples here how use them - like https://root.cern/js/latest/api.htm#custom_html_tmultigraph

**WebEve** is different project. It is about of online display of 3D event data like tracks or hits on top of detector geometry. Plus many other useful features. Project is in early development phase, but we hope to have preliminary code in main ROOT repository soon (this autumn).

**Comment by Axel-Naumann** [comment]
Eve7 / REve is much advanced now: you can try out `tutorials/eve7/calorimeters.C`. We're happy to continue a discussion on https://root-forum.cern.h - this doesn't really look like a bug report :-) Thanks!
