### ISSUE TITLE
Fail to find function JSROOT.Painter.drawTree after loading tree

### ISSUE THREAD

**Issue by cozzyd** [root-project/jsroot#148]
I am working on a "slow" (updated once a day) monitoring page using jsroot where I open a ROOT file containing a TTree and try to draw some branches from it, but I get an alert with the message: 

Fail to find function JSROOT.Painter.drawTree after loading tree

It seems like perhaps I didn't specify the right requirements when loading the script (I have 2d, io and tree), or somehow JSROOTTree is loaded before JSROOTPainter so JSROOT.Painter.drawTree never gets instantiated? Or maybe I'm doing something completely wrong.  

Here's a minimal example: 
```

<html>
<head>
<script type="text/javascript" src="../jsroot/scripts/JSRootCore.js?2d&io&tree"></script>
<script>

function load() 
{
  var filename = "all_hk.root";
  JSROOT.OpenFile(filename, function(file) {
  file.ReadObject("hk;1", function(obj) {
  JSROOT.draw("drawing", obj, "temp_master:temp_slave");
  });
  });
}
</script>
</head>

<body onLoad="load()">

<div id="drawing"></div> 
</body>
</html>


```

**Comment by linev** [comment]
In dev version I provide better solution. Now following code should work:

    <script type="text/javascript" src="http://jsroot.gsi.de/dev/scripts/JSRootCore.js"></script>
    <script>
        var filename = "http://jsroot.gsi.de/files/hsimple.root";
       JSROOT.OpenFile(filename, function(file) {
           file.ReadObject("ntuple;1", function(obj) {
             JSROOT.draw("drawing", obj, "px:py");
          });
      });
     </script>

**Comment by cozzyd** [comment]
Thanks! That works.
