### ISSUE TITLE
Nonstandard lines colors

### ISSUE THREAD

**Issue by DanielWielanek** [root-project/jsroot#150]
Hi,
I'm trying to draw TGraph with black background and white lines (root file attached as pdf)with code:
[scan.pdf](https://github.com/root-project/jsroot/files/1831580/scan.pdf)
and display with simple code:

``` 
<meta charset="UTF-8">
<html>
<head>
<script src="nica_js/scripts/JSRootCore.js" type="text/javascript"></script>
</head>
<body>
<script type='text/javascript'>
  var filename = "scan.root";
 JSROOT.OpenFile(filename, function(file) {
    JSROOT.gStyle.Palette= 50;
    file.ReadObject("c1;1", function(obj) {
       JSROOT.draw("drawing", obj, " ");
    });
  });
</script>
<div id="drawing" style="width:90%; height:900px"></div>
</body></html> 
```

But only part of lines is white (ticks). I used dev version of JsROOT + ROOT 6.08. For default colours it works.

**Comment by linev** [comment]
Hi Daniel,

You are right - axis color was not used correctly for grids.
Also main axis line was not drawn with correspondent color.
Now should be fixed in "dev" and "master" branches:

http://jsroot.gsi.de/dev/?file=../files/tmp/scan.root&item=c1

Thanks for reporting the problem :+1: 
Sergey

**Comment by linev** [comment]
Now in official [5.4.1.](https://github.com/root-project/jsroot/releases/tag/5.4.1) release
