### ISSUE TITLE
Display png in grid

### ISSUE THREAD

**Issue by pionkaon** [root-project/jsroot#151]
Hi,

I am using jsroot for some online monitoring. I'm generating root graphs and histograms and viewing them in a grid from a web browser - it all works great including monitoring. 

I also have some graphs that are produced by an external process and saved in a directory as pngs (I have no control over this process). 
I'd like to include these graphs in the grid with the root graphs and histograms. 
So I load them into root as a TImage and write them into a TMemFile (containing my other historgrams) like this.

img = ROOT.TImage.Open('test_graph.png')
img.Write()

From a jsroot browser I can see test_graph.png in the file but when I click on it it doesn't render.
Similarly I can't seem to directly display it in an iframe. 

Is it just that this is not implemented in jsroot ?
Or is there an easier way that I am missing ?

If not would it be simple to implement - just a pass through of drawing the png - then I could have it rendered as part of a jsroot grid with the root histograms / graphs ?

Thanks.

**Comment by linev** [comment]
Hi,

JSROOT does not support reading images from ROOT files.
I recommend to use png images directly and insert them in HTML, using `<img>`
node.

Regards,
Sergey

**Comment by pionkaon** [comment]
ok - shame - is it possible to include them in a jsroot grid with an <img> tag ?

**Comment by pionkaon** [comment]
That should have read "with an \<img\> tag"

**Comment by pionkaon** [comment]
(I have quite a few graphs to include so would rather use the grid functionality rather than a lot of iframes)

**Comment by linev** [comment]
If you asking about usage of layout elements like this:

https://root.cern/js/latest/api.htm#url_syntax_veritcal_layout

In principle, there is special JSROOT class behind, 
but I do not have examples how such class can be used.

But if you can place different `<div>` elements on HTML page, some of such elements could be used for the JSROOT drawings and another can be used for inserting `<img href="your_server/img.png"/>` tags

**Comment by pionkaon** [comment]
Yes, that's exactly the kind of layout I was thinking of.

I suppose I could use CSS grid and have one section containing a jsroot layout as above and another section containing the image.

Just out of curiosity is there any special difficulty that you can think of with making jsroot display images from root files ?  (I might have a go at trying to add it myself if it's not too much work.)

Many thanks.

**Comment by linev** [comment]
> I suppose I could use CSS grid and have one section containing a jsroot layout as above and another section containing the image.

Yes, this is preferable solution.

> Just out of curiosity is there any special difficulty that you can think of with making jsroot display images from root files ? (I might have a go at trying to add it myself if it's not too much work.)

There is no problem to read TImage class from the ROOT file. But one should find a way to produce HTML Image out of such binary data. 

If you want, I can provide you some entry points in JSROOT, where you could try to implement this.

**Comment by pionkaon** [comment]
That would be great - thanks :)

**Comment by bellenot** [comment]
What about embedding the image in HTML: `<img src="data:image/png;base64,xxxxxxxxx...`?

**Comment by linev** [comment]
> What about embedding the image in HTML: <img src="data:image/png;base64,xxxxxxxxx...?

This could be one possible solution. But main question - how to produce such string from TImage?

**Comment by pionkaon** [comment]
I can take a look at the underlying library that root uses - maybe there is a function to convert to a more friendly format.

**Comment by pionkaon** [comment]
Was just thinking it would be nice to include it into the jsroot layout.

**Comment by bellenot** [comment]
> This could be one possible solution. But main question - how to produce such string from TImage?

Good question...

**Comment by pionkaon** [comment]
Ok looking at it might be easier to just load the png (or svg) file directly into the jsroot layout if I knew where the hooks were

**Comment by linev** [comment]
Hi

TASImage uses custom streamer. I implement it, but only for the case when image stored as PNG buffer. To see raw data members:

http://jsroot.gsi.de/dev/?file=../files/tmp/rose.root&item=rose&opt=inspect

I also make entry point if you want try to extract image from that raw buffer and create **Image** out of it. Draw function is here:

https://github.com/root-project/jsroot/blob/dev/scripts/JSRootPainter.more.js#L3400-L3416

But if you want to use normal images together with JSROOT drawing, look on this example:

http://jsroot.gsi.de/dev/api.htm#custom_html_read_root_file
http://jsroot.gsi.de/dev/api.htm#custom_html_read_root_file_src

Just add `<img>` element(s) and assign src attribute for it.

**Comment by pionkaon** [comment]
Thanks - just been working through this.

It looks like 

// main.append("img").attr("src","https://root.cern/js/files/img/tf1.png");

version is what I would need - probably easiest to just include the image directly from the webserver


I did find this call in TImage (TASImage)

void TASImage::GetImageBuffer(char **buffer, int *size, EImageFileTypes type)

but I'm working in python3 but haven't been able to test it as I can't figure out how to pass by ref the 'int *size'

**Comment by pionkaon** [comment]
GetImageBuffer()

Return in-memory buffer compressed according image type.

Buffer must be deallocated after usage. This method can be used for sending images over network.

**Comment by linev** [comment]
> It looks like
> // main.append("img").attr("src","https://root.cern/js/files/img/tf1.png");
> version is what I would need - probably easiest to just include the image directly from the webserver

This is just demo how external image can be inserted. 
Here one does not need TASImage at all.

> I did find this call in TImage (TASImage)
> void TASImage::GetImageBuffer(char **buffer, int *size, EImageFileTypes type)

I cannot help too much here. One need to understand that kind of information stored in TASImage.
*fPngBuf*, which you see [here](http://jsroot.gsi.de/dev/?file=../files/tmp/rose.root&item=rose&opt=inspect), applied to the image by TASImage::SetImageBuffer() [here](https://root.cern/doc/master/TASImage_8cxx_source.html#l06216).

**Comment by pionkaon** [comment]
1) Yes - can see that's without using TASImage

2) I've been trying to see if I can create a buffer from a png file and call SetImageBuffer to populate a TASImage object  - no luck yet - think I will just stick with 1) if I can't get it to work.

Is it possible to load a png image from a file through the url interface ?

**Comment by linev** [comment]
> Is it possible to load a png image from a file through the url interface?

It can be implemented - but only via url parameters.

**Comment by pionkaon** [comment]
That would be good too if you have time to do it !

Thanks for your help anyway - I'm sure I can get something going now.

**Comment by linev** [comment]
Hi,

Now you can provide `item=img:http://server/file.png` and options "center" or "scale"

Here is example: http://jsroot.gsi.de/dev/api.htm#url_syntax_images

You need to use dev version from http://jsroot.gsi.de or "dev" branch from the repository

**Comment by pionkaon** [comment]
That is AWESOME !  Exactly what I was thinking of.

Thank you very much :)

**Comment by pionkaon** [comment]
Just a quick question about this - should this work ?

item=img:../files/img/file.png

I checked out the dev branch and pointed JSROOTSYS at it but I can't seem to seem to get it to work with the file.png in $JSROOTSYS/files/img/file.png

This however does work

serv.AddLocation('mydir/', '/home/temp')

and then 

item=img:http://127.0.0.1:8080/mydir/file.png

**Comment by linev** [comment]
> This however does work

> serv.AddLocation('mydir/', '/home/temp')

> and then

> item=img:http://127.0.0.1:8080/mydir/file.png

When you are using THttpServer, this is the only solution.

> item=img:../files/img/file.png

This kind of link only works with default "index.htm" file of JSROOT. And path defined relative to that HTML page. With THttpServer address is "localhost:8080" and relative address is different.

I do not recommend to use JSROOTSYS location for your custom PNG images.

**Comment by pionkaon** [comment]
Ok - understood - thanks for the explanation.

**Comment by linev** [comment]
Solution now in latest [stable](https://github.com/root-project/jsroot/releases/tag/5.5.0) release
