### ISSUE TITLE
Call stack limit on Chrome

### ISSUE THREAD

**Issue by cozzyd** [root-project/jsroot#154]
I have an application where I interactively produce TGraphs from ROOT trees (each corresponding to a different run; what runs are plotted  are selected by the user) and then plot them using TMultiGraphs. If there are enough TGraphs globally (even if in different TMultiGraphs in different divs), I run into the call stack limit on Chrome 65. Firefox 59 has no problem. Firefox 52 also reaches its recursion limit. 

I guess this is because I am drawing too many objects and it probably has nothing to do with TGraph or TMultiGraph.  It looks to me that the base painter is shared  globally, and so all draw operations go onto the same callback stack, which I guess will eventually exceed whatever the browser limits are. If each div had its own callback stack, then perhaps it would be possible to draw more things (as long as they are not all on the same plot)?

**Comment by linev** [comment]
> If there are enough TGraphs globally (even if in different TMultiGraphs in different divs), I run into the call stack limit on Chrome 65. Firefox 59 has no problem. Firefox 52 also reaches its recursion limit.

How much TGraphs all together you have?
Does [this](https://root.cern/js/latest/?nobrowser&file=../files/bigcanvas.root&item=big) canvas work for you?

Most  probably, you start drawing of next graphs from the callback function of previous JSROOT.draw(). And if there are too many of such calls, you can get a problem. Simplest solution here would be to issue short timeout and continue drawing afterwards. By this technique  you will release previous stack.

**Comment by cozzyd** [comment]
The big canvas does indeed work. 

The example where it fails has just over 2500 TGraphs, over three divs
(two of which have 1140 graphs).  I haven't figured out the minimum
number of graphs to fail, but I can if you think it's important. I pool
the TGraphs together into TMultiGraphs, but I suppose that chains the
calls together. 

I have a separate JSROOT.draw( ) for each div and it works for the
first TMultiGraph of 1140 TGraph's but not the second. If I just draw
the second div by itself it works fine, so there seems to be some
global state even between divs and separate draw() calls. I will try a
timeout to see if it works around the issue.

**Comment by linev** [comment]
> (two of which have 1140 graphs)

It is fairly big. This should be implemented inside TMultiGraph.

This is already done on TCanvas level - therefore big canvas works for you.
I will check next week.

**Comment by linev** [comment]
Now your example should work - I insert timeout every 500 graphs.
This should avoid very deep stacks

**Comment by linev** [comment]
I apply that small fix in dev and master branch.
During this week I will produce 5.4.1 bugfix release, which will include correspondent fix

**Comment by linev** [comment]
Now fix in [5.4.1](https://github.com/root-project/jsroot/releases/tag/5.4.1) release

**Comment by cozzyd** [comment]
Thanks, can confirm large numbers of graphs plot correctly in Chrome.
