### ISSUE TITLE
Problem loading .root files with OpenFile

### ISSUE THREAD

**Issue by hcbeck** [root-project/jsroot#157]
Hi, 

I have a online monitoring page for a collection of graphs (using `JSROOT.NewHttpRequest()` and `JSROOT.draw()`  and wanted to add some reference graphs to the plot. The references are stored in .root files on the server. I tried to loaded the file and the specific reference with this code: 
`JSROOT.OpenFile(Testfile.root, function(file){
    file.ReadObject(histname, function(obj){
        JSROOT.draw("drawing-div", obj, "hist");});
    });`

I tried this first with JsRoot version 4.8.0 because of dependencies I could not update. With this version the graph is loaded but this error is reported in firefox console (which did not bother me to much because the graph was displayed):

Expact boundary --"56abcf75c9af76a84"  got --56abcf75c9af76a84 JSRootIOEvolution.js:1214:22
	read_callback "serverXY"/lib/JsRoot480/scripts/JSRootIOEvolution.js:1214:22
	callback "serverXY"/lib/JsRoot480/scripts/JSRootCore.js:609:51
	JSROOT.NewHttpRequest/xhr.onreadystatechange "serverXY"/lib/JsRoot480/scripts/JSRootCore.js:678:13 

"serverXY" replaced.
Now I updated to version 5.4.1 and the graphs are no longer loaded especially the `file` in the callback is `null`. Also a similar/same error is reported:

Decode multipart message, expect boundary  --"56abfe6d1051a4a3c" got  --56abfe6d1051a4a3c  JSRootIOEvolution.js:1069:22
	TFile.prototype.ReadBuffer/read_callback "serverXY"/lib/JsRoot541/scripts/JSRootIOEvolution.js:1069:22
	callback "serverXY"/lib/JsRoot541/scripts/JSRootCore.js:768:51
	JSROOT.NewHttpRequest/xhr.onreadystatechange "serverXY"/lib/JsRoot541/scripts/JSRootCore.js:828:10

I tried this also without a server just loading the page in the browser and then the loading works.
My question would be whether the loading of .root files is intended like this or I should do this differently?  Perhaps you know what causes this error?

Thank you for your response, 
Helge

**Comment by linev** [comment]
Hi,

This is about decoding of multipart messages from http servers (used now to read data from ROOT files). Such message separated by leading/trailing tags. And seems to be, these tags not absolutely equal on your server:

    header: --"56abfe6d1051a4a3c" 
    trailer: --56abfe6d1051a4a3c 

Normally they should be identical. I could implement workaround for such mismatch. 
Can you test it fast today?

**Comment by hcbeck** [comment]
Hi, 

thank you for the reply. I could test this today in the next 2 hours or early tomorrow. 
Do you know whether there is a common place where I could check my server for the header and trailer?

**Comment by linev** [comment]
> Do you know whether there is a common place where I could check my server for the header and trailer?

Have no idea. These are very special http requests.

**Comment by hcbeck** [comment]
I tested it and it works with my server. Thank you very much for the quick help. I will try to talk to the server expert to see if these quotes are correct. But I do not expect a quick answer.
