### ISSUE TITLE
Displaying of few fit function

### ISSUE THREAD

**Issue by bdrum** [root-project/jsroot#159]
Hello, Sergey(@linev) 

I catched some problem:

This is original image getting from my script. 
![factimage](https://user-images.githubusercontent.com/16210997/40645391-e1491f8a-632e-11e8-94a4-47656a893b65.png)

But unfortunately in some reasons, in js root browser I see this one:
![screenshot from 2018-05-29 10 52 30](https://user-images.githubusercontent.com/16210997/40645447-066accb4-632f-11e8-8bf1-ff370a317b66.png)

As you can see something wrong with displaying fit functions. It shows only one fit function.

So, how I understood the problem something wrong inside the process of filling fFunctions for TH1 object, because at the moment of drawing it has only 2 functions - "stats" and first from TH1::GetListOfFunctions()

You can find my example in this file:

[fewFitters.root.zip](https://github.com/root-project/jsroot/files/2047969/fewFitters.root.zip)

Boris

**Comment by linev** [comment]
I see the problem - when histogram drawn with "same" options, attached functions are ignored.

**Comment by linev** [comment]
This feature was introduced some years ago to prevent JSROOT from drawin stats box for all histograms, drawn with "same" draw option. Now JSROOT able to handle many stat boxes, therefore such limitations is no longer necessary - I removed it.

**Comment by bdrum** [comment]
Many thanks, Sergey! Now everything is fine.
