### ISSUE TITLE
Upgrading from 5.1.1 to 5.2 causes plots not be drawn

### ISSUE THREAD

**Issue by nasfarley88** [root-project/jsroot#160]
Upgrading from 5.1.1 to 5.2 causes plots not be drawn, with no errors, but the console acts as if it has been drawn. 

E.g.
```
JSROOT.draw(dom_element, root_object);
```
works for 5.1.1 and 5.2.0, with the same console output:

`Extract basic data type 3 TH1::EBinErrorOpt`

**Comment by linev** [comment]
Can you provide data which does not work?

**Comment by nasfarley88** [comment]
Sure, all of our data has this problem so I assumed it was due to some change in the API. I'll upload it later today.

**Comment by nasfarley88** [comment]
This contains some of the plots that are not showing. It's from a standalone test for GEANT4.

[RMSResults.root.zip](https://github.com/root-project/jsroot/files/2079639/RMSResults.root.zip)

**Comment by bellenot** [comment]
Note that with you file, in ROOT 5, I got those warnings:
```
root [2] Warning in <TStreamerInfo::BuildOld>: Cannot convert TF1::fParErrors from type:vector<double> to type:Double_t*, skip element
Warning in <TStreamerInfo::BuildOld>: Cannot convert TF1::fParMin from type:vector<double> to type:Double_t*, skip element
Warning in <TStreamerInfo::BuildOld>: Cannot convert TF1::fParMax from type:vector<double> to type:Double_t*, skip element
Warning in <TStreamerInfo::BuildOld>: Cannot convert TF1::fSave from type:vector<double> to type:Double_t*, skip element
Warning in <TStreamerInfo::BuildOld>: Cannot convert TF1::fParams from type:TF1Parameters* to type:Double_t*, skip element
```
So it might be related...

**Comment by linev** [comment]
Hi,

I can read and display all histograms from your file:

https://root.cern/js/latest/?file=../files/tmp/RMSResults.root&item=[3]

The only problem - spaces in the histogram names. 
One should use special syntax like:

https://root.cern/js/latest/index.htm?file=../files/tmp/RMSResults.root&item=%27Distribution%20for%20Energy%20%201000;1%27

Regards,
Sergey

**Comment by nasfarley88** [comment]
@linev What does this use behind the scenes to draw the plots? Has there been some change to the JSROOT.draw method which might cause it to draw in the official example but not in our application?

@bellenot I *think* that should be OK, we are all using ROOT 6 at the moment

**Comment by linev** [comment]
> What does this use behind the scenes to draw the plots? Has there been some change to the JSROOT.draw method which might cause it to draw in the official example but not in our application?

It depends how you use this method. Basic functionality is the same.
Only return value is changed. If you want to to access painter instance, you should use forth callback parameter now:

https://root.cern/js/dev/jsdoc/JSROOT.html#.draw

**Comment by nasfarley88** [comment]
Hmm, I think I've found it. For some reason, with 5.1 the canvas was being resized, whereas with 5.2 it's not resized when `JSROOT.draw` is called. I'm pretty sure we were using some undocumented behaviour to have automatic resizing so I'm happy to close and reopen if we find something more concrete.

**Comment by linev** [comment]
> For some reason, with 5.1 the canvas was being resized, whereas with 5.2 it's not resized when JSROOT.draw is called.

Probably, you are right. 
At some point I disable set of canvas pixel size to html element - it may conflict with layout of other html elements. Dimension of div element for canvas should be provided by user.
