### ISSUE TITLE
Draw colz with text option

### ISSUE THREAD

**Issue by aminnj** [root-project/jsroot#162]
Hi, 

Is there a way to draw a TH2 with colz and text overlayed (similar to `h2.Draw("colztext")`)?

Thanks,
Nick

**Comment by linev** [comment]
Hi Nick,

For now use "textcolz" draw option: 

https://root.cern/js/latest/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=textcolz

I will fix code, that "colztext" also can be used.

Regards,
Sergey

**Comment by aminnj** [comment]
Thanks! I didn't think to even try textcolz. It works perfectly.

**Comment by linev** [comment]
Now also "colztext" should work - I improve decoding of draw options string.
Will be in next bugfix release next week

**Comment by aminnj** [comment]
Great, thanks a lot!

**Comment by linev** [comment]
Now available in [latest](https://github.com/root-project/jsroot/releases/tag/5.5.0) release
