### ISSUE TITLE
Usage of functions before their loading

### ISSUE THREAD

**Issue by vladimirkosmala** [root-project/jsroot#163]
Many functions have an async loading like `JSROOT.draw`. Others don't like `JSROOT.resize` and should be loaded before call or **TypeError: JSROOT.resize is not a function** is rised.

Calling `draw` will load `resize` implicitly, but too late if done at the same time.
Same with the loading options `?2d`, it is loaded async to `JSROOT.resize` could rise error.

For now best options I have are:
- force loading sync by putting <script> tags
- or just check before calling of `if (JSROOT.resize)`, because of course there is nothing to resize before drawing so it suits the needs but I feel it not elegant, though.

What do you think?

**Comment by linev** [comment]
Only central functions like `JSROOT.OpenFile()` or `JSROOT.draw()` have async interface. 
And yes - JSROOT.resize makes sense only when something was drawn. 
Second solution with `if (JSROOT.resize)` statement would be preferable. Or if you would like, you always can use [AssertPrerquisities](https://root.cern/js/dev/jsdoc/JSROOT.html#.AssertPrerequisites):

    JSROOT.AssertPrerequisites("2d", function() {
        JSROOT.resize("element_id");
    });

**Comment by vladimirkosmala** [comment]
Understood, `AssertPrerequisites` is an elegant solution too.

Thanks
