### ISSUE TITLE
TObjString drawing

### ISSUE THREAD

**Issue by vladimirkosmala** [root-project/jsroot#164]
Would it be possible to draw TObjString?

I see in ROOT there is no method `draw()` so it is normal that JSROOT does not handle it either. 

So I see two possibilities:
- parsing object and recognize a TObjString before giving it to `JSROOT.draw()` and print a raw text instead by other means. But I don't like much the fact of having a second ROOT lib in addition to JSROOT.
- eventually integrate it to JSROOT so it shows the string in a canvas with d3.js

Do you think it's possible? I seen TString is handled already by JSROOT.

Json file:
https://www.dropbox.com/s/9cmiwtmcq64qlff/daqTask_hello.json?dl=0

Root file:
https://www.dropbox.com/s/hlzjyhdfz9kjdz8/daqTask_hello.root?dl=0

**Comment by linev** [comment]
> I seen TString is handled already by JSROOT.

Where you see this?

> Would it be possible to draw TObjString?

Yes, I can implement.
I have function for plain text display. 
I can reuse it for the TObjString.

**Comment by linev** [comment]
Just try my https://jsroot.gsi.de/dev/ version - should work now

**Comment by vladimirkosmala** [comment]
Ok, perfect!

I seen TString  in source code, but may be it was as a sub-property.
