### ISSUE TITLE
react app and jsroot

### ISSUE THREAD

**Issue by mvala** [root-project/jsroot#165]
I would like to use jsroot in react app. I am using defautl react bundle from https://github.com/facebook/create-react-app and i installed jsroot via npm

In my App component i and doing
```
import JSROOT from 'jsroot/scripts/JSRootCore'
```
and i am getting error
```
./node_modules/jsroot/scripts/JSRootCore.js
Cannot statically analyse 'require(..., ...)' in line 1316
```
Can you give me hint what do to make it work correctly?

**Comment by mvala** [comment]
You can test it on https://github.com/mvala/react-jsroot-example . One just do
```
npm install
npm start
```
Adn you should be able to reproduce it

**Comment by linev** [comment]
Hi,

First of all, I never used react and webpack.

    Cannot statically analyse 'require(..., ...)' in line 1316

I made fast search about such kind of errors.

It is about analyzing code and producing bundles of scripts, which can be load fast afterwards.
Problem with JSROOT, that such list of scripts is dynamic and depends from the application and classes, which one wants to display. Therefore static analyzer fails. 

I guess, you need to find a way to instruct webpack manually which JSROOT scripts should be loaded. Maybe one need to put some special comments into the code. In worse case just specify all JSROOT scripts - like I did it [here](https://github.com/root-project/jsroot/blob/master/demo/gulp/bower.json)  to produce concatenated script with gulp. 

Regards,
Sergey

Regards,
Sergey

**Comment by mvala** [comment]
I see your point. And i found the way, bu i need to turn off automatic loading of dependency in jsroot. Is it posible?

**Comment by linev** [comment]
> And i found the way, bu i need to turn off automatic loading of dependency in jsroot. Is it posible?

If you loads all necessary JSROOT scripts yourself - it should work.
JSROOT should not to try load such scripts again - at least it was designed that way.

**Comment by mvala** [comment]
Ok, but it is not working as expected. I am not next to my laptop now, but i will try to reproduce it for you.

**Comment by dmatis2** [comment]
@linev that comments do you mean this? 

`/* global JSROOT */` 

?

**Comment by linev** [comment]
> that comments do you mean this?
> /* global JSROOT */

When JSROOT loaded as normal JavaScript, global variable with name **JSROOT** is declared.
This is how you can use functions like `JSROOT.draw()`. In case when require.js is used, global variables is not declared - you should use handle returned with `define()` method.

**Comment by mvala** [comment]
I think i can handle it via https://www.npmjs.com/package/react-async-script-loader, but i have problem that when i load script 'https://root.cern.ch/js/latest/scripts/JSRootCore.js?jq2d' i need to find out when all modules are loaded. is there any function can give me this info? Or is there a way that loading of scripts will be done sequentially?

**Comment by mvala** [comment]
Is there way to find out that all modules are loaded?

**Comment by mvala** [comment]
Ok. Thanks for feedback and i am waiting for hint.

**Comment by mvala** [comment]
I understand that i can find list of modules. But loading of dependencies is async. I would need to know when loading is finished. Some function that is triggered when loading is done

**Comment by mvala** [comment]
Ok. I will try

**Comment by mvala** [comment]
I tried and and callback it called before all modules are loaded. Here is console output from browser
```
Loading of modules is done JSRootBrowser.js:50
loading https://root.cern.ch/js/latest/scripts/jquery.min.js ... JSRootCore.js:264:10
loading https://root.cern.ch/js/latest/scripts/jquery-ui.min.js ... JSRootCore.js:264:10
loading https://root.cern.ch/js/latest/scripts/d3.min.js ... JSRootCore.js:264:10
loading https://root.cern.ch/js/latest/scripts/JSRootPainter.js ... JSRootCore.js:264:10
```

**Comment by linev** [comment]
> I tried and and callback is called before all modules are loaded. 

Strange. 
Do you calling function many times? 
Or maybe you specify extra URL parameters when loading JSRootCore.js script?

**Comment by mvala** [comment]
My bad. I put myfun() and i should put myfun

**Comment by A-lxe** [comment]
@mvala Any chance you can show how you got things working?

**Comment by mvala** [comment]
I just published experimental npm package `@obsk/react-jsroot@0.3.0`

Source code is here : https://gitlab.openbrain.sk/obsk/react-jsroot
There is demo app : https://gitlab.openbrain.sk/obsk/react-jsroot/tree/master/src/demo
