### ISSUE TITLE
Changing color on redraw

### ISSUE THREAD

**Issue by vladimirkosmala** [root-project/jsroot#167]
- Currently redraw call changes curve according to new values, but if color has changed it stay the same.
- Needed: like curve, colors should be updated too.

To reproduce:
- draw a chart with a fillColor
- redraw same chart with different fillColor
- output as not changed

Data example:
https://pastebin.com/3Rx1hkPw

fFillColor integer can be replaced to simulate color changing.

This feature is used for passing from a green to red color for example, if data indicate danger/error values.

**Comment by linev** [comment]
Here is example how redraw with different fill color can be done:   

http://jsroot.gsi.de/files/tmp/read_color.htm

Main part of the example:

     var filename = "../hsimple.root";
     JSROOT.OpenFile(filename, function(file) {
        file.ReadObject("hpx;1", function(obj) {
           obj.fFillColor = 3;
           obj.fFillStyle = 1001;
           JSROOT.draw("drawing", obj, "f", function() {
              setTimeout(function() {
                 obj.fFillColor = 2;
                 JSROOT.redraw("drawing", obj, "f");
              }, 5000);
           });
        });
     });

**Comment by vladimirkosmala** [comment]
Indeed, I confirm this option works.
