### ISSUE TITLE
Convert geometry from .root file to .json.gz

### ISSUE THREAD

**Issue by dmatis2** [root-project/jsroot#168]
I have an issue that I'd like to use this https://root.cern/js/latest/api.htm#custom_html_tgeo_src but I have a root file with .root extension https://alieos.saske.sk//eos/alike.saske.sk/scratch/mpd_full.root 

How can I convert it to the proper format ?

**Comment by linev** [comment]
Hi

You can also directly use root file.
Looks how histogram from root file:

https://root.cern/js/latest/api.htm#custom_html_read_root_file_src

Same can be applied for geometry.

**Comment by linev** [comment]
You can display it like this:

https://root.cern/js/latest/?file=https://alieos.saske.sk//eos/alike.saske.sk/scratch/mpd_full.root&item=FAIRGeom

**Comment by dmatis2** [comment]
```
import React, { Component } from 'react';
import scriptLoader from 'react-async-script-loader';

class JSRootGeo extends Component {

  init = () => {
      const { JSROOT } = window;
      var geom_file = "https://alieos.saske.sk//eos/alike.saske.sk/scratch/mpd_full.root"
      JSROOT.OpenFile(geom_file, function(file) {
        file.ReadObject("hpxpy;1", function(obj) {
           JSROOT.draw("drawing", obj, "colz");
        });
     });
  }

  render() {
    const { isScriptLoaded, isScriptLoadSucceed } = this.props;
    let component = <h1>Loading</h1>;

    if (isScriptLoaded && isScriptLoadSucceed) {
      const { JSROOT } = window;
      component = null;
      JSROOT.AssertPrerequisites("jq2d", this.init);
    }

    return (
      <div>
        {component}
        <div id="drawing" style={{"width":800, "height":600}}/>
      </div>
    );
  }
}


export default scriptLoader(
  'https://root.cern.ch/js/latest/scripts/JSRootCore.js'
)(JSRootGeo);
```

I'm doing it like this using ReactJS but nothing is shown... In console there is only `Extract basic data type 3 TGeoMaterial::EGeoMaterialState`

**Comment by linev** [comment]
You should specify correct object name and draw options:

       file.ReadObject("FAIRGeom;1", function(obj) {
            JSROOT.draw("drawing", obj, "");
        });

**Comment by dmatis2** [comment]
Thank you very much :)

**Comment by mvala** [comment]
we would like to use tracks also, do we need to convert t to json.gz?
Like it it in 
https://root.cern/js/latest/api.htm#custom_html_tgeo_src

**Comment by linev** [comment]
You also can read tracks from root file - just insert tracks loading and drawing inside call back function of JSROOT.draw() call for geometry. Just check file name.

**Comment by mvala** [comment]
Can we reuse file?

**Comment by linev** [comment]
> Can we reuse file? Because we have tracks also in that file in "Tracks"

Yes, you can.
