### ISSUE TITLE
Simple GUI - opening a file on a remote server with http parameters produces too many http requests

### ISSUE THREAD

**Issue by akveton** [root-project/jsroot#169]
Given the simple gui for root file browsing (https://jsroot.gsi.de/latest/?), I want to be able to open a generated file using a parametrized http request.

So for example, I have a http request like this, where viewer.html is the simple gui:

http://127.0.0.1:1081/viewer.html?file="http://127.0.0.1:1081/getfile?table=MON_HCAL_NGRBX_PerHERBX&column=mezz_WTE_cnt&prescaler=1&time_start=1514821000&time_end=1539095860&positive_fetch=false"

/getfile is an endpoint which generates a root file given 6 parameters.

This works, but the request is sent 6 times (note: same number of times as the number of parameters). Is this a bug, or is this simply not supported? Is there any way to achieve this in a nice way? I don't want to have to resort to creating my own syntax of http parameter dictionary (note: the whole thing works fine, when it's just one parameter (i.e. no ampersands or quotes - just two question marks)

For example, this parametrized query works (again, viewer is the simple gui):

http://pccodb00/logbook/?p=viewer&file=http://pccodb00/logbook/show_rootfile.php?runnb=286554

**Comment by linev** [comment]
Hi,

> This works, but the request is sent 6 times (note: same number of times as the number of parameters)

Explanation is simple - by default JSROOT uses partial file access and make several HTTP requests to read different parts of the file. To overcome this problem, you need to add "+" sign at the very end of the file name. Like:

https://root.cern/js/latest/?nobrowser&file=../files/hsimple.root+&item=hpx;1

In this case complete file content will be read with single HTTP request. 
Of course, size of such file cannot be too large.

**Comment by akveton** [comment]
That's very helpful, thank you! It works exactly as you said. I wish I had known it was this simple.
