### ISSUE TITLE
Interactive Editing of TAxis

### ISSUE THREAD

**Issue by JHiltbrand** [root-project/jsroot#170]
I have noticed that when interacting with a JSRoot plot embedded in a webpage that I can right-click on an axis to change various properties (label size, color etc), great! After completing such an operation I seem to not be able to right-click on the axis anymore, I only get the "Frame" menu to pop up. I just demonstrated it now with this example https://root.cern.ch/js/latest/api.htm#custom_html_read_root_file. I was wondering if this had already been reported and/or if was just me.

**Comment by linev** [comment]
Yes, you are right. I will check it.

**Comment by linev** [comment]
Thanks for reporting this! 
Now fixed. 
You could try it with https://jsroot.gsi.de/dev/ version
