### ISSUE TITLE
fLabelSize Attribute in JSON for z-axis

### ISSUE THREAD

**Issue by JHiltbrand** [root-project/jsroot#171]
I have wrote my own ROOT to JSON class the defines a TH1 or TH2 in JSON format (since I am not able to use the latest ROOT with the TBufferJSON...). I define the fAxis section in the JSON for all three axis using the same function and the x-axis and y-axis respond to different fLabelSize parameters while the z-axis does not apparently. I have attached a canvas output to demonstrate what I am looking at. Again I am not sure if this a misunderstanding of ROOT on my part or if this is a quirk in JSRoot.

![canvas](https://user-images.githubusercontent.com/13418669/46784033-d7592980-cd2c-11e8-9b65-4892ce95b6d5.png)

**Comment by JHiltbrand** [comment]
> Means you are using ROOT5? If JSON does not work for you - you can store histograms in ROOT files.

Yeah, I have to use ROOT5 and I have the histogram in proper ROOT format to work with, hence I can just pass it to my own conversion class.

> It is true - palette ignores label and font settings. I will fix it.

Awesome, thanks!

**Comment by linev** [comment]
Done - you can try version https://jsroot.gsi.de/dev/
