### ISSUE TITLE
broken interactivity: axes and histogram frozen and line not drawn upon TF1::Draw("SAME")

### ISSUE THREAD

**Issue by sidebo** [root-project/jsroot#173]
I'm trying to plot a histogram and its fitted function on the same pad, with the different components of the model drawn separately in different colours. Somehow the Draw("SAME") causes the plot to "freeze" partly: I can no longer scroll to zoom on the axes and the histogram style can not be altered. Furthermore, the SAME-plotted function is not visible. When the plot is saved however (through TCanvas::SaveAs), everything is in fact there. 

With this notebook the problem can be reproduced (can be executed directly if one has pyROOT): https://github.com/sidebo/sh1015-opendatalab/blob/master/problem-jsroot/jsroot-problem-reproducible.ipynb

**Comment by linev** [comment]
Hi,

Sorry, I cannot run your notebook now. But from the code I could guess that problem is here:

     fBW = ROOT.TF1("BW", "[0]*TMath::BreitWigner(x, [1], [2])", xlow_fit, xup_fit)

Function exists on C++ side, but does not work in JSROOT.
Can you store produced TCanvas in ROOT file and attach it here?
I will check that kind of solutions can be provided.

**Comment by linev** [comment]
I checked your example within normal ROOT macro.
First of all, I implement BreitWigner function in the ROOT:

https://github.com/root-project/jsroot/commit/1722160ebb5c519ed4cde69a10de21da590bb147

But it only appears later and only solves problem with your specific example.
JSROOT cannot calculate all kinds of functions, but this calculation can be done before drawing it.
Just add following code to your macro before drawing:

     fBW.Save(xlow_fit, xup_fit,0,0,0,0);
     fBkg.Save(xlow_fit, xup_fit,0,0,0,0);
     fModel.Save(xlow_fit, xup_fit,0,0,0,0);

This should solve your problem

**Comment by sidebo** [comment]
Thanks a lot for your prompt replies. Indeed it works. I'm confused though--without the `.Save` I could still draw `fModel` with JSROOT, and that function is equal to Breit-Wigner+other function. Do you understand why that's possible?

Also, it would be great if this was caught somehow and an error message printed. Now the user is a bit clueless and might think something is wrong with the code (ROOT side)

**Comment by linev** [comment]
> I could still draw fModel with JSROOT, and that function is equal to Breit-Wigner+other function. Do you understand why that's possible?

My explanation - for some components fitter store points, using same Save() method. 

> Also, it would be great if this was caught somehow and an error message printed. 

Typically errors can be seen in the browser console (Ctrl + Shift + I). It is not trivial to catch them properly and communicate back to ROOT side - especially in case of iPython Notebooks. 

But yes - I will try to improve error handling.
