### ISSUE TITLE
Fractional integral values in statistics panel

### ISSUE THREAD

**Issue by aminnj** [root-project/jsroot#179]
In 5.6.1, if I draw a histogram and right click the statistics panel > SetOptStat > check Integral, I can only get integer values of the integral, even though my histogram has sumw2 information embedded. Is this intentional?

Locally I deleted the `"entries"` from
https://github.com/root-project/jsroot/blob/9d7ad747d49029758ad5f113d18581c8af1341f9/scripts/JSRootPainter.hist.js#L3635
and that seems to give me a few decimal places.

I haven't verified properly with the cutting edge version, but the link above is from master and has `"entries"` so I guess it will still round the integral.

**Comment by linev** [comment]
Yes, for integral values less than 1e9 JSROOT uses rounding.
I can improve it - although ROOT itself does not consistent in this place. Sometimes ROOT uses rounding for integral, sometimes not - with the same histogram.

**Comment by linev** [comment]
Now problem should be fixed - jsroot will not use rounding for float numbers.
I will try to produce bugfix release 5.6.3 this week

**Comment by linev** [comment]
Now 5.6.3 tag is there - https://github.com/root-project/jsroot/releases/tag/5.6.3
@aminnj  - thank you for reporting the problem, it helps to fix another one.

**Comment by aminnj** [comment]
Thanks a lot! Also on this topic, is there an easy way to show the integral in the stat box by default, preferably by adding something to the url (e.g., at the end of `index.htm?file=files/tth_histos_srcr_2018.root`)

**Comment by linev** [comment]
URL parameter name is `optstat`. Like:

https://root.cern/js/latest/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=colz&optstat=1111111

I will try to add docu about it.
