### ISSUE TITLE
createXtruBuffer seems to ignore XY offsets for layers

### ISSUE THREAD

**Issue by altavir** [root-project/jsroot#182]
I am not able to test it right now, but from the source code it seems like fX0 and fY0 parameters are ignored.

**Comment by linev** [comment]
Very well could be.
I need test-case - simple geometry with `xtru` shape. And I will try to fix the problem - or you can do it as well. It should be straightforward.

**Comment by altavir** [comment]
I will be able to test separate shapes when I finish writing converters to jsRoot format. Sadly, I was not able to use the whole `TGeoManager` renderer. It does not work with the json export sample I was given. Maybe root version incompatibility problem. So now, I am using base GDML format and thin adapters to jsRoot dynamic shape definitions.

**Comment by linev** [comment]
I implement a fix. Already test shapes from examples have X0/Y0 set:

http://jsroot.gsi.de/dev/?nobrowser&file=../files/geom/geodemo.root&item=xtru;1&opt=za

In dev version already three.js version 102 is used.

**Comment by linev** [comment]
@altavir Thanks for reporting the problem!

**Comment by linev** [comment]
>  So now, I am using base GDML format and thin adapters to jsRoot dynamic shape definitions.

You intend to read GDML files directly from JavaScript and convert them into TGeo classes for JSROOT? 
Why not to use ROOT GDML import and store geometry in ROOT or JSON format? 
This will save you a lot of work.

**Comment by altavir** [comment]
I am using only front-end part of JSRoot for now. And I will probably have to replace even those in future because JSON-serialized root classes not always compatible with JSROOT (I tried a JSON exported from root and it does not work) and have size about 1Mb. For now, I take gdml directly and use thin adapters for JSRoot `createGeometry` (basically I have to just replace `pSomething` with `fSomething`).

The ultimate goal is to have thin JS client that can load data from remote ROOT-based server (and other servers) and render it. I hoped to use parts of JSRoot as is, but sadly, ROOT serialization is not suitable for remote call purposes (not stable enough and not compact enough).

My team will still try to contribute to this project. Maybe split rendering API into more convenient modules and provide external communication protocol.

**Comment by linev** [comment]
> because JSON-serialized root classes not always compatible with JSROOT (I tried a JSON exported from root and it does not work) and have size about 1Mb

Strange. In most cases ROOT C++ -> JSON conversion works pretty well.
Only classes with custom streamers are not supported, but can be instrumented for such purposes.
Do you have examples when it does not work?

And 1Mb should not be a big problem - did you try compression and spaces reduction?
In many cases gzip-ed json files have similar size as ROOT binary files.

**Comment by altavir** [comment]
I will open another issue for it then.
