### ISSUE TITLE
Incompatibility with root json export

### ISSUE THREAD

**Issue by altavir** [root-project/jsroot#183]
The issue is split from #182 discussion.

The initial root file and expanded json from it. The problem is with references which are expanded incorrectly.
[root.zip](https://github.com/root-project/jsroot/files/3038951/root.zip)

Of course, I we could work past those incompatibilities, we would like to have both global root export and manual object creation at the same time.

**Comment by linev** [comment]
Both files - ROOT and JSON works for me. 
If I gzip json, it is smaller than binary file.

**Comment by linev** [comment]
If I do following command:

```
TBufferJSON::ExportToFile("test.json.gz", gGeoManager, "3");
```
I get file which 25% smaller than binary ROOT file (30Kb instead of 40 Kb).
But on this level difference is not important in my mind - one can choose any of this formats.

Here is result:

http://jsroot.gsi.de/dev/?json=../files/tmp/test.json.gz

**Comment by altavir** [comment]
OK, then It is possible, I use it in a wrong way. I pass it directly to [build](https://github.com/root-project/jsroot/blob/a4be12d0543e8de6f747d147819baa5274460c20/scripts/JSRootGeoBase.js#L3239) function. And it fails because the the top volume is a reference.

**Comment by altavir** [comment]
It seems like I need to run `JSROOT.JSONR_unref` before passing object to a renderer. I will try to do it and see if it works. Thanks.

**Comment by linev** [comment]
In general, you should use `JSROOT.parse()` for json, produced with TBufferJSON in ROOT.

**Comment by altavir** [comment]
Thanks. I will look into the code further.
