### ISSUE TITLE
Unnamed TPaveTexts are not handled properly

### ISSUE THREAD

**Issue by Barthelemy** [root-project/jsroot#190]
In ROOT (desktop) one can add unnamed TPaveTexts to an histogram and display them without issues. I don't actually know anyone naming each and every element of their plots. 

In JSROOT, it appears that unnamed TPaveTexts are not handled properly. Upon refreshing the histogram the first TPaveTexts "disappears". 

There has been some private discussions by email between a colleague and Serguei but I would like to raise the issue more openly here. 

Although we have ways of working around the issue, they are impractical and really only patches. We have dozen of users who decide what objects they want to publish and all we do is transport and display them. We can't tell them to name every element, because any ways they will always forget some. We should therefore ourselves go through every element and set a random name if there is none, which raises serious performance concerns.

In my opinion, this is a bug and as such must be fixed in JSROOT itself. Having unnamed elements, in particular TPaveTexts, is not forbidden by ROOT and thus should be handled in a non breaking way by JSROOT.

**Comment by linev** [comment]
I tried to implement fix for the problem.
It is not universal solution, but should cover more usecases.
Originally only statbox from histogram lists of functions was aimed.
Now original canvas (with similar names in TPaveText) works:

http://jsroot.gsi.de/files/tmp/debugging.html

You can download and try dev version from jsroot.gsi.de

**Comment by Barthelemy** [comment]
Thank you very much, we are going to test it and let you know.
