### ISSUE TITLE
CORS request behaviour changed with Firefox 68

### ISSUE THREAD

**Issue by gollumben** [root-project/jsroot#191]
Hi,
in the documentation:

https://github.com/root-project/jsroot/blob/master/docs/JSROOT.md#reading-root-files-from-other-servers

you suggest to avoid same-origin policy problems by copying the index.htm and changing two lines. This does not work with Firefox >67 in all cases any more:

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

Example case: Do as described in an environment away from a server environment, such as in your home directory on your local computer.

Cheers,
Ben

**Comment by linev** [comment]
Hi Ben,

That is not working in newest Firefox - reading files from local disks. It was possible before.

But avoiding CORS by copying index.htm file together with ROOT file should works. Like: 

http://jsroot.gsi.de/nocors/?file=hsimple.root&item=hpxpy&opt=colz
http://jsroot.gsi.de/nocors/read_file_cors.htm

Folder `nocors/` does not have special configuration with `Access-Control-Allow-Origin="*"` header.

Regards,
Sergey

**Comment by gollumben** [comment]
Hi Sergey, thanks, these are two fantastic examples!
