### ISSUE TITLE
How to retrieve custom colors in a canvas

### ISSUE THREAD

**Issue by gollumben** [root-project/jsroot#192]
Dear Sergey, Dear team,

I am trying to use JSROOT to plot some ROOT canvases containing custom-defined TColors. Since the definitions of these colors are not saved in the .root files, I need to redefine the colors when drawing the canvases with JSROOT. Do you have a suggestion what would be the best way to do so? My idea was to add the colors to the .root file somehow and to have JSROOT redefine them when opening the file, maybe using the script option. Would you potentially have a code snippet?

I apologise if the same issue was raised by someone else in the past.

Thanks and Cheers,
Ben

**Comment by linev** [comment]
Hi Ben,

> I am trying to use JSROOT to plot some ROOT canvases containing custom-defined TColors. Since the definitions of these colors are not saved in the .root files, I need to redefine the colors when drawing the canvases with JSROOT. 

Actually, custom colors are stored with TCanvas in ROOT file. But not in all situations.
Algorithm if following:
1. Create new custom TColor instances - at least 51
2. Create TCanvas and draw objects there
3. Store TCanvas in the ROOT file

In this case list of all colors will be stored and used in JSROOT.

Another solution - store list of colors as separate object into ROOT file and "adopt" it in JSROOT before perform any other drawing. Demo is here:

http://jsroot.gsi.de/latest/api.htm#custom_html_adopt_colors
https://github.com/root-project/jsroot/blob/master/demo/adopt_colors.htm

Regards,
Sergey

**Comment by gollumben** [comment]
Hi Sergey,
thank you for this explanation. I prepared following code following your algorithm in pyROOT
```
from ROOT import TCanvas, TColor, TH1F, TFile
import ROOT


c = TCanvas()
c.Draw()

h1 = TH1F("h1", "histo from a gaussian", 100, -3, 3)
h1.FillRandom("gaus", 10000)

#style options
ci = ROOT.TColor.GetFreeColorIndex()
color = TColor(ci, 0/255., 168/255., 196/255.)
h1.SetFillColor(ci)

h1.Draw()

c.SaveAs("outputImage.png")
c.SaveAs("outputImage.root")
```
Unfortunately, I am not able to see the colors in JSROOT. What am I doing wrong?

Thank you again and Cheers,
Ben

**Comment by linev** [comment]
You need to create at least 51 new colors objects - only then they will be stored in TCanvas.
Functionality was originally implemented to store custom palette colors

**Comment by gollumben** [comment]
Hi Sergey,
thank you for your response! I implemented saving the colors in my .root files. For future reference, I used
```python
rootColorList = ROOT.gROOT.GetListOfColors()

of = TFile("myFile.root", "RECREATE")
of.WriteTObject(canvas)
of.WriteTObject(rootColorList)
of.Close()
```
to retrieve the colors and save canvas and colors. Then using the example you provided, I am reading in the files and displaying them.
```html
<!DOCTYPE html>
<html lang="en">
<head>

   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">

   <title>Reading object from the ROOT file</title>
Information: Loading of the files can take some seconds.
   <script src="https://root.cern/js/latest/scripts/JSRootCore.min.js?io&2d&onload=DrawMg" type="text/javascript"></script>

   <script type='text/javascript'>
	function findGetParameter(parameterName) {
	    var result = null,
		tmp = [];
	    location.search
		.substr(1)
		.split("&")
		.forEach(function (item) {
		  tmp = item.split("=");
		  if (tmp[0] === parameterName) result = decodeURIComponent(tmp[1]);
		});
	    return result;
	}

     // absolute file path can be used as well
     var filename = findGetParameter("ifile");
     //var filename = "outputImage.root";
     function DrawMg() {
        JSROOT.OpenFile(filename, function(file) {
          file.ReadObject("ListOfColors", function(obj) {
           JSROOT.Painter.adoptRootColors(obj);
           file.ReadObject("canvas", function(obj_g) {
              JSROOT.draw("drawing", obj_g, "AL");
           });
           file.ReadObject("canvas2D", function(obj_g) {
              JSROOT.draw("drawing", obj_g, "AL");
           });

          });
        });
     }
   </script>

</head>

<body>
  <div id="drawing" style="width:800px; height:600px"></div>
</body>

</html>
```
Is there a way I can make the loading bar display when I open a .root file?

**Comment by linev** [comment]
> Is there a way I can make the loading bar display when I open a .root file?

Progress bar not supported for normal objects reading - only for TTree I/O. 
Do you have so large TCanvas objects that it makes sense?
You could use following function to show some info during objects loading:
```
        JSROOT.progress("Opening file " + filename);
        JSROOT.OpenFile(filename, function(file) {
          JSROOT.progress("Reading colors list");
          file.ReadObject("ListOfColors", function(obj) {
           JSROOT.Painter.adoptRootColors(obj);
           JSROOT.progress("Reading canvas");
           file.ReadObject("canvas", function(obj_g) {
              JSROOT.progress("done", 1000);
              JSROOT.draw("drawing", obj_g, "AL");
           });
          });
        });
```


In your HTML code you loads two canvases, but uses drawing in the same `<div>` element - is it intentional? While I/O is asynchronous, there is no guarantee which canvas will be displayed at the end.

**Comment by gollumben** [comment]
Hi Sergey,
thank you for your reply! I added these status bars and it works like a charm. I am hosting things on lxplus/eos and as a problem seems to be that the servers are slow, something that I wanted to give the user access to the status.

I am loading two canvases to the same `<div>`, correct. The reason I am doing that is because the files I am trying to open either contain the canvas `canvas` or the canvas `canvas2D`. I guess it would be nicer to use an `if-contains` condition, but I do not know, how I could implement that with JSROOT.

Thanks again and Cheers,
Ben

**Comment by linev** [comment]
> I am loading two canvases to the same <div>, correct. The reason I am doing that is because the files I am trying to open either contain the canvas canvas or the canvas canvas2D. I guess it would be nicer to use an if-contains condition, but I do not know, how I could implement that with JSROOT.

After you open file, you could check yourself which objects are there.
There is `file.fKeys` array of TKey objects, and you can use it like:
```
for (var n=0;n<file.fKeys.length;++n) {
   if (file.fKeys[n].fName == "canvas2D") draw_canvas2d(); 
   else if (file.fKeys[n].fName == "canvas") draw_canvas(); 
}
```

**Comment by gollumben** [comment]
Btw, changing ROOT's behaviour of saving colors is discussed here
https://root-forum.cern.ch/t/tcolor-not-saved-in-canvas-root-output/36876/8
