### ISSUE TITLE
how to invert the y axis

### ISSUE THREAD

**Issue by jvo203** [root-project/jsroot#193]
How would you invert the Y-Axis of TH2 so that it points down, not the usual up? In C/C++ ROOT the following code, found on the ROOT forum, does the trick (one also needs to invert/swap the underlying histogram bins but this is trivial).

No amount of searching the Internet gives any hints on how to do it in JSROOT. This functionality is absolutely vital when displaying the Hertzsprung-Russell Diagram in astronomy. The Y-Axis displays the magnitude (see https://en.wikipedia.org/wiki/Hertzsprung%E2%80%93Russell_diagram).

The example C/C++ code:
```
ReverseXAxis (TH1 *h)
{
   // Remove the current axis
   h->GetXaxis()->SetLabelOffset(999);
   h->GetXaxis()->SetTickLength(0);

   // Redraw the new axis
   gPad->Update();
   TGaxis *newaxis = new TGaxis(gPad->GetUxmax(),
                                gPad->GetUymin(),
                                gPad->GetUxmin(),
                                gPad->GetUymin(),
                                h->GetXaxis()->GetXmin(),
                                h->GetXaxis()->GetXmax(),
                                510,"-");
   newaxis->SetLabelOffset(-0.03);
   newaxis->Draw();
}
```

This is a major stumbling block. Many thanks.

**Comment by linev** [comment]
This is just workaround in ROOT. 
Normal axes drawing is disabled and extra axis drawn on the top.

Something like that could be done with JSROOT.
One requires one histogram for axis drawing and another to show content.

https://root.cern/js/latest/?file=../files/hsimple.root&item=[hpxpy;1,hpxpy;1]&opt=[AXIS_RX_RY,COL]

First histogram uses options AXIS_RX_RY. Means draw only axes and revert X and Y axis.
Second histogram just draw on the top.

**Comment by linev** [comment]
You can also move axes on other side:

https://root.cern/js/latest/?file=../files/hsimple.root&item=[hpxpy;1,hpxpy;1]&opt=[AXIS_RXX+_RYY+,COL]

But it is difficult to display axes on both sides.
The only chance - try to create ROOT TCanvas and show it with JSROOT.
TGaxis object should be displayed in same way.
But of course, interactive zooming will not work properly.

**Comment by jvo203** [comment]
Hi, Thank you, your first response is exactly what is needed in this case. There is no need to draw Y axes on both sides. Just the inverted magnitude shown on the left hand side is sufficient.

**Comment by jvo203** [comment]
Hi Sergey,

Sorry to bother you again. There is just one slight issue with your solution. As per the attached PDF file with my website, the first graph with the inverted y axis does not show the colour palette on the right hand side, nor does hovering a mouse over any bin pop up a small window with bin information. The other two graphs below have the colour palette and hovering a mouse triggers an info pop up (also notice the effect of JSROOT.gStyle.fOptLogz = 1; on graphs).

[GAIA DR2 WebQL.pdf](https://github.com/root-project/jsroot/files/4074693/GAIA.DR2.WebQL.pdf)

Is there any way (any additional option) to re-enable there lost features for the inverted graph too? This is the JavaScript code I use (the .root files are compressed, hence the use of JSROOT.TFile to load them):

```
function fetch_plots() {
    console.log("fetching plots for " + uuid);

    $('#completed').remove();
    JSROOT.gStyle.fOptLogz = 1;

    new JSROOT.TFile("DATA/" + uuid + "/hr.root", function (file) {
        file.ReadObject(uuid + "::HR", function (obj) {
            // draw only axes and revert the Y axis
            JSROOT.draw("hr", obj, "AXIS_RY");
            // overlay the actual histogram on top of the axes
            JSROOT.draw("hr", obj, "COLZ");

            var html = '<p>M<SUB>G</SUB> = phot_g_mean_mag + 5 + 5 log<SUB>10</SUB>(parallax / 1000)';

            if (where != "")
                html += ', where ' + where;

            html += '</p>';

            $('#mg').append(html);
        });
    });

    new JSROOT.TFile("DATA/" + uuid + "/xy.root", function (file) {
        file.ReadObject(uuid + "::XY", function (obj) {
            JSROOT.draw("xy", obj, "colz");
        });
    });

    new JSROOT.TFile("DATA/" + uuid + "/rz.root", function (file) {
        file.ReadObject(uuid + "::RZ", function (obj) {
            JSROOT.draw("rz", obj, "colz");
        });
    });
}
```

**Comment by jvo203** [comment]
Another side effect of inverting the y axis: zooming with a scroll-wheel over the inverted histogram bins shows an incorrect zoomed area. The mouse coordinates used by the zoom function do not seem to reflect the fact that a user is zooming-in an inverted histogram. It's as if the inversion has never taken place and the zoom function looks at the original uninverted data/Y-axis.

**Comment by linev** [comment]
At the moment reversed axes is just a hack in JSROOT.
Therefore most interactive features does not work.
I need to implement them correctly, but this can take a lot of time.

**Comment by jvo203** [comment]
I see. In that case is there a way to disable the interactive parts for that first HR plot (or actually two overlaid graphs)? Disable/hide the interactive square menu located under the plot to the left as well as disable mouse interaction (zooming, bin statistics under the mouse pointer etc).

Once the interactive functionality in JSROOT is 100% ready we will enable it in our website.

**Comment by linev** [comment]
There are several parameters in JSROOT.gStyle object. See comments here:

https://github.com/root-project/jsroot/blob/master/scripts/JSRootCore.js#L151-L164

You can change these parameters before making JSROOT drawing.

**Comment by jvo203** [comment]
Thank you. Is it OK to disable certain global options before making the first (static) plot and then to re-enable them to make subsequent interactive plots? I mean if I re-enable global interactive options to plot interactive graphs, would those re-enabled options not make the first static graph interactive again?

Will play with those options next week.

**Comment by linev** [comment]
> Is it OK to disable certain global options before making the first (static) plot

No, these are global options and affect all JSROOT drawings.

One could disable tooltip for specific histogram adding "notooltip" to draw options:

https://root.cern/js/latest/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=col;notooltip

But zooming settings are always global and should not be changed after drawing performed

**Comment by linev** [comment]
Hi,

Originally "rx" and "ry" options were introduced for axes drawing of TGraph. 
Now I try to add support of reverted axes also for TH2 col drawing. 
Here is example:

http://jsroot.gsi.de/dev/examples.htm#th2_col_rx_ry

You can use master branch of JSROOT.
If you need some other drawing options support with reverted axes - please let me know.
In some cases it can be done relatively easy, in other could be problematic.

**Comment by jvo203** [comment]
It's looking good! The palette can be switched on from the bottom menu, bin values show, log-z is OK. Only mouse zooming does not reflect the inverted coordinates yet (surely it is a matter of time...)!

**Comment by linev** [comment]
> Only mouse zooming does not reflect the inverted coordinates yet (surely it is a matter of time...)!

That do you mean?

**Comment by jvo203** [comment]
When a mouse pointer is positioned say over the left-hand side, upon zoom-in with a mouse wheel the right-hand side is expanded. Always the opposite part of the image is zoomed-in.

**Comment by linev** [comment]
Also zooming with mouse wheel should work now

**Comment by jvo203** [comment]
Thank you very much. Indeed it works. Selecting a rectangular sub-region with a mouse also works correctly.

By the way, is there a reason why the colour palette on the right-hand side does not appear  by default in your example? It has to be enabled from the bottom menu. In my plots the palette always appears by default.

I would like to incorporate the master JSROOT in our website. Is there an easy way to redirect users to the master branch of JSROOT (with your fixes) instead of the latest stable (which does not contain your fixes)? When do you anticipate a new stable release might be made with the latest improvements?

At present this is the way JSROOT is inserted into HTML within C++:
```
// CERN ROOT JS
  std::string url =
      "https://root.cern/js/latest/scripts/JSRootCore.min.js?more2d&io&onload=";

  if (!exists)
    html.append("<script type=\"text/javascript\" "
                "src=\"" +
                url + "onloaded\"></script>");
  else
    html.append("<script type=\"text/javascript\" "
                "src=\"" +
                url + "fetch_plots\"></script>");
```

**Comment by jvo203** [comment]
"If you need some other drawing options support with reverted axes - please let me know.
In some cases it can be done relatively easy, in other could be problematic."

Yes, here is an easy request! At present you have added the option below which reverses both the X and Y axes.

{ opt: "col_rx_ry", title: "reverse x and y axis with col drawing" },

In our HR plot we only need to reverse the Y axis. The X axis stays the same. Would it be easy to add separate options "col_rx" and "col_ry" to reverse only one of the two axes?

In addition "colz" shows the colour palette by default. Would it be easy to enable the palette by default with "col_rx_ry", "col_rx" and "col_y"? Alternatively add an extra set of options like "col_ry_z" etc. with the palette "on" by default? What do you think?

Many thanks.

**Comment by jvo203** [comment]
Better yet why not have two sets of options:

 "col_rx_ry", "col_rx" and "col_ry"

and

 "colz_rx_ry", "colz_rx" and "colz_ry" with a colour palette on by default?

**Comment by linev** [comment]
I add "col_rx_ry" just for automatic testing of JSROOT. You always can configure options as you want:

http://jsroot.gsi.de/dev/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=colz_rx
http://jsroot.gsi.de/dev/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=colz_ry

**Comment by jvo203** [comment]
I see! In that case how easy is it to swap out the latest stable release and switch to the master JSROOT? Ideally just by changing the url in
```
std::string url =
      "https://root.cern/js/latest/scripts/JSRootCore.min.js?more2d&io&onload=";
```

**Comment by linev** [comment]
Until next JSROOT release you can use `https://jsroot.gsi.de/dev/` or `https://root.cern/js/dev/` (will be updated later today). Like:

    "https://root.cern/js/dev/scripts/JSRootCore.min.js?more2d&io&onload=";

**Comment by jvo203** [comment]
Hi Sergey,

Many thanks, have updated our server C/C++ code and the client-side JavaScript accordingly. "COLZ_RY" is now working OK.
