### ISSUE TITLE
TH2D draw options "VIOLIN" and "CANDLE" not supported in jsroot?

### ISSUE THREAD

**Issue by akveton** [root-project/jsroot#194]
Using http://jsroot.gsi.de/latest/, if I open a TH2D drawn with the "VIOLIN" or "CANDLE" option, it fails to display properly.

What is shown:
![](https://i.imgur.com/2uoWJAk.png)

Expected behavior as seen in desktop root:
![](https://i.imgur.com/9Fc0ODI.png)

[Link to the root file in question](https://mega.nz/#!iokhFYaC!2gCGv5lId_2XMPmEzwVV_5ITZs5RPh_uq5CG2ie3IkM)

Is there any method how to make this work or are there plans to fix this? Thanks!

**Comment by linev** [comment]
Hi,

CANDLE plot is partially implemented:

https://root.cern/js/latest/examples.htm?more#th2_candle

VIOLIN is not supported yet.

Both options are not trivial, while require different statistical calculations.
If you are willing to contribute - I can help with integrating such drawing into JSROOT

**Comment by akveton** [comment]
> Hi,
> 
> CANDLE plot is partially implemented:
> 
> https://root.cern/js/latest/examples.htm?more#th2_candle
> 
> VIOLIN is not supported yet.
> 
> Both options are not trivial, while require different statistical calculations.
> If you are willing to contribute - I can help with integrating such drawing into JSROOT

Hello, thank you for the quick reply! 

If CANDLE works then that is good enough for our usecase I think. Could you please elaborate on how it is limited, given its partial implementation?

Thanks for this great tool that is jsroot, by the way!

**Comment by linev** [comment]
> If CANDLE works then that is good enough for our usecase I think. Could you please elaborate on how it is limited, given its partial implementation?

See here:

https://github.com/root-project/jsroot/blob/master/scripts/JSRootPainter.hist.js#L5528-L5638

I implement CANDLE options while ago, now in ROOT there are much more details can be configured with CANDLE drawing. One should adopt actual code from TCandle class into JSROOT.

**Comment by akveton** [comment]
From the source code, it is not very obvious to me how to achieve the drawing of a plot like the one you showed in the example. 

What we are doing is generating root files in pyroot, which are then fed to the jsroot browser.

If I do histogram.Draw("CANDLEX(11111111)") in pyroot and then display that file the jsroot browser, many of the essential features (that are present in your example) are missing. Could you please provide the parameters or method that was used to achieve a result like in your example? Thanks in advance!

**Comment by linev** [comment]
Once again - many features of CANDLE plot not implemented in JSROOT.
I do not plan any big improvements,  but you could try to implement required features yourself.

**Comment by linev** [comment]
`CANDLE` and `VIOLIN` draw options are now implemented in master:

https://jsroot.gsi.de/dev/examples.htm#candle_stack
https://jsroot.gsi.de/dev/examples.htm#candle_decay
