### ISSUE TITLE
setting fOptLogz locally (per-plot) from JavaScript

### ISSUE THREAD

**Issue by jvo203** [root-project/jsroot#195]
```JSROOT.gStyle.fOptLogz = 1;``` sets the log-scale globally for all affected plots. However, in our case some plots should not be using the logarithmic scale as the Z axis contains negative values too. Hence there is a requirement to enable fOptLogz per-plot programmatically during drawing (not by a user clicking a mouse, going to the small menu and doing it manually).

The compressed ROOT plots are loaded in the following way:

```
new JSROOT.TFile("DATA/" + uuid + "/xy.root", function (file) {
        file.ReadObject(uuid + "::XY", function (obj) {
            JSROOT.draw("xy", obj, "colz");
        });
    });
```

How can it be achieved in JSROOT?

**Comment by jvo203** [comment]
One solution (a workaround) I have found is to enable ```JSROOT.gStyle.fOptLogz = 1;``` globally and plot the TH2 histogram objects as usual with the logz scale enabled by default.

Plots that should not be using logz are exported from C/C++ as TCanvas objects instead and displayed with ```JSROOT.draw```. JSROOT TCanvas objects are not subject to the global style options anymore since they have been generated in C/C++ on the server side. It is a workaround but this works fine.

**Comment by linev** [comment]
One should be able to use "logz" draw option for histograms:

https://root.cern/js/latest/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=colz,logz

In your case just try:

    JSROOT.draw("xy", obj, "colz;logz");

**Comment by jvo203** [comment]
Thank you, your suggestion works.
