### ISSUE TITLE
TLatex rendering problems

### ISSUE THREAD

**Issue by jvo203** [root-project/jsroot#196]
As per the attached PDF files, Greek letters do not appear in the web site despite enabling mathjax in the JSROOT URL ```std::string url = "https://root.cern/js/dev/scripts/"
                    "JSRootCore.min.js?more2d&3d&io&mathjax&onload=";```

[Greek letters.pdf](https://github.com/root-project/jsroot/files/4120416/Greek.letters.pdf)

The Phi still literally appears as Phi (see for example the second plot from the bottom). In the C/C++ it is set as per below:
```set_title(uuid + "::XYVPhi", "X-Y-V_{\\Phi}", "X [kpc]", "Y [kpc]", "V_{\\Phi} [km/s]");```

LaTeX-style subscript is respected by JSROOT but the Greek letter is ignored.

**Comment by jvo203** [comment]
```\overline{V}``` does seem not work either. It gets displayed literally...

**Comment by jvo203** [comment]
OK. Have nearly fixed it. Doing ```global_hist._xyvphi.set_title(uuid + "::XYVPhi", "X-Y-#bar{V}_{#Phi}",
                                    "X [kpc]", "Y [kpc]",
                                    "#bar{V}_{#Phi} [km/s]");``` fixes the Greek letter as well as the overline in the z-axis. But the plot title does not show the overline, only the Greek letter Phi has been fixed.

It can be seen in the fifth plot from the top (X-Y-V_{Phi}).

[missing overline in the title.pdf](https://github.com/root-project/jsroot/files/4121026/missing.overline.in.the.title.pdf)



Z-Axis title is set with ```_hist->GetZaxis()->SetTitle(z_title.c_str());```
The main title is set in the constructor ```_hist = new TProfile2D(name.c_str(), title.c_str(), NBINS3, x_min, x_max,
                         NBINS3, y_min, y_max, z_min, z_max);```

Something is going wrong LaTeX parsing of the main plot title...

**Comment by jvo203** [comment]
The problem seems to be browser-dependent. #bar in the main plot title displays OK in macOS Safair. But does not display in Chrome under Linux. Firefox in Linux is affected too.

**Comment by linev** [comment]
First of all - `#overline` does not supported by TLatex and also not by JSROOT.

`#bar{X}` work for me on Linux with Firefox and Chrome.

Greek letters in JSROOT should be specified as `#phi`, not as `\\Phi`

There are some other limitations.
By default, JSROOT uses own TLatex parsing and rendering. Unfortunately, it is not complete and does not handle correctly complex cases like `#bar{X_{y}}`. But when `mathjax` option specified in URL, parsing is fully performed by MathJax.js and works for me correctly. 

Can you provide TLatex expression which does not work for you?

**Comment by jvo203** [comment]
Yes, I replaced \overline with #bar and \\Phi with #Phi so they are parsed correctly. Using either ```math``` or ```mathjax``` results in the strange behaviour of the main title. The Z-Axis title is displayed correctly though! To add insult to injury, smaller plots seen at the bottom of the attached PDF show the main title correctly!

The "offending" (for the main title only) pseudo-LaTeX is this: "X-Y-#bar{V}_{#Phi}".

[inconsistent latex handling.pdf](https://github.com/root-project/jsroot/files/4121442/inconsistent.latex.handling.pdf)

**Comment by linev** [comment]
Do you mean: `X-Y-{#bar{V}}_{#Phi}` or `X-Y-#bar{{V}_{#Phi}}`

Both working with mathjax rendering for me.
I checked - `overline` supported by mathjax, I will try to add support into JSROOT

**Comment by linev** [comment]
Now you can use `#overline` with https://jsroot.gsi.de/dev/ version.

**Comment by jvo203** [comment]
Hi, Am using the dev jsroot. With the official ```std::string url = "https://root.cern/js/dev/scripts/"
                    "JSRootCore.min.js?more2d&3d&io&mathjax&onload=";``` ```#overline``` does not work yet (overline is displayed literally). 

With jsroot.gsi.de
```std::string url = "https://jsroot.gsi.de/dev/scripts/"
                    "JSRootCore.min.js?more2d&3d&io&mathjax&onload=";```

there is neither the text "overline" nor any upper bar at all. You can see the attached PDF.

[no overline at all.pdf](https://github.com/root-project/jsroot/files/4125939/no.overline.at.all.pdf)

This is the TLatex expression: ```"R-Z-#overline{{V}_{#Phi}}"```

**Comment by jvo203** [comment]
With jsroot.gsi.de, using #bar instead of #overline does not help (there is no overline displayed at all, neither in the title nor in the z-axis). Perhaps there are some bugs in the rendering engine itself???

**Comment by jvo203** [comment]
This problem is almost certainly due to a combination of TLatex parsing problems as well as rendering and/or font problems either within jsroot or on the web browser side.
Using 
```/ an early development version
  std::string url = "https://jsroot.gsi.de/dev/scripts/"
                    "JSRootCore.min.js?more2d&3d&io&mathjax&onload=";```

and ```X-Y-#overline{V}_{#Phi}``` (originally intended ```R-Z-#overline{{V}_{#Phi}}``` does not work at all, TLatex in JSROOT cannot parse it) produces mixed results that depend on the OS used.

**Comment by linev** [comment]
`X-Y-#overline{V}_{#Phi}` should work now with jsroot.gsi.de/dev/ version (also master branch in github). Please cleanup your browser cache. I also trying to implement primitive rendering of underline/overline without MathJax, but this will takes some time

**Comment by jvo203** [comment]
I've tested #overline with both https://jsroot.gsi.de/dev and https://root.cern/js/dev. After clearing the cache, at present it seems #overline only works with https://jsroot.gsi.de/dev. By "works" I mean with strange rendering problems. I have finally replaced all the large X-Y-#overline{V} plots with a set of smaller plots for the mean and std. Right now those smaller plots also suffer from missing overlines. The results can be seen here (using https://jsroot.gsi.de/dev):

[GAIA DR2 WebQL.pdf](https://github.com/root-project/jsroot/files/4126801/GAIA.DR2.WebQL.pdf)

It seems as if the fonts are getting clipped at the top. This causes the overline to disappear. But setting the top margin to say 0.2 did not help. Perhaps some adjustments need to be made to the margin handling or clipping at the top of the fonts??? The graphs were generated as TCanvas in C/C++. (I tried to export the left TProfile2D and right TH2D directly from C/C++ without TCanvas but they refuse to be drawn in JSROOT inside a HTML table. So there is a need to keep using TCanvas).

**Comment by jvo203** [comment]
Here is the final product that works pretty much OK with https://root.cern/js/dev. The #overline has been deleted,  replaced by #bar. Now the overline shows OK on both the left-hand and right-hand side smaller plots. 

[overline shows OK.pdf](https://github.com/root-project/jsroot/files/4126832/overline.shows.OK.pdf)

**Comment by linev** [comment]
Yes, I did not update root.cern/js/dev/ version yet, while I still try to improve simplified JSROOT rendering of TLatex.

**Comment by jvo203** [comment]
Hi Sergey, here is an interesting hint as to what is happening on my side. The problem seems occur only when the TCanvas object exported from C/C++ is displayed at its original resolution by the ```JSROOT.draw()```. When the large TCanvas is down-scaled by ```JSROOT.draw()``` to fit a smaller HTML element the #bar is displayed correctly.

Test environment: ```std::string url = "https://root.cern/js/dev/scripts/"
                    "JSRootCore.min.js?more2d&3d&io&math&onload=";``` (math, not mathjax)
TLatex: ```"R-Z-#bar{V}_{#Phi}"```

See the last two images in testing.pdf. The original size of the larger image is ```1000x600```. The #bar is missing. When the same image is down-scaled to ```500x300``` (see the very last plot), as if by magic the #bar is displayed correctly. So the rendering problems somehow seem to be related to the image scaling routines used either by JSROOT, ds3.js or a web browser.

[testing.pdf](https://github.com/root-project/jsroot/files/4131805/testing.pdf)

**Comment by linev** [comment]
> (math, not mathjax)

When you not activate MathJax, simplified JSROOT rendering is performed. And it is not fully reliable. Main problem is correct scaling of text. In this case image resolution play important role. 
I do not have much time to improve it now

**Comment by jvo203** [comment]
That's alright. From our point of view, the important parts display pretty much OK at present.

**Comment by linev** [comment]
I guess, I can close issue.
If you have any questions - feel free to reopen it.
