### ISSUE TITLE
self-hosting of JSROOT

### ISSUE THREAD

**Issue by jvo203** [root-project/jsroot#197]
To speed up initial loading of JSROOT scripts across continents, at present JSROOT is loaded via cdn.jsdelivr.net (we copied the "scripts" and "style" folders):

```
std::string url = "https://cdn.jsdelivr.net/gh/jvo203/GAIAWebQL/htdocs/gaiawebql/scripts/JSRootCore.js?more2d&3d&io&mathjax&onload=";

  if (!exists)
    html.append("<script defer type=\"text/javascript\" "
                "src=\"" +
                url + "onloaded\"></script>");
  else
    html.append("<script defer type=\"text/javascript\" "
                "src=\"" +
                url + "fetch_plots\"></script>"); 
```

However, it seems three files are still being loaded from the ROOT CERN server: "MathJax.js",  "TeX-AMS-MML_SVG.js" and "color.js", which adds about 2s to the loading time.

Would it be possible for you to modify JSROOT so that these files are loaded from the "scripts" folder, which we can then replicate across continents via cdn.jsdelivr.net?

**Comment by linev** [comment]
Hi,

Use of mathjax is optional. It has to be used with `TMathText` class - which is very exotic - and optionally with `TLatex` - when mathjax opion specified in URL.

While mathjax is huge - we never tried to distribute with JSROOT. 

You can specify your own location of mathjax - just replace three occasions in JSRootCore.js where `https://root.cern/js/mathjax/latest` appears. We test code with relatively old MathJax version 2.7, but probably newer versions will work as well

**Comment by jvo203** [comment]
OK. Thank you.
