### ISSUE TITLE
D3.js bundled version always triggers an error

### ISSUE THREAD

**Issue by avivace** [root-project/jsroot#198]
JSRootPainter has a routine to check the version of D3 in use. However, the default shipped version (in the releases found [here](https://github.com/root-project/jsroot/releases)) of D3 *always* triggers this error.

```
Very old d3.js 3.5.17 found, please UPGRADE JSRootPainter.js:37:18
    <anonyme> http://localhost:8080/scripts/JSRootPainter.js:37
```

Why not include a version not triggering this error (>=4)? Or consider showing that message as as a simple log/warning?

**Comment by linev** [comment]
By default, JSROOT shipped with d3.js version  5.7.0. But if other d3.js version loaded before JSRootCore.js - it will be used but warning is issued. If possible, just load JSROOT before loading such old d3.js

**Comment by avivace** [comment]
This happens with the last [release](https://github.com/root-project/jsroot/releases/tag/5.8.1). I didn't add anything else but the libraries included in the shipped tar.gz

**Comment by linev** [comment]
Here is example web page from latest release:

https://root.cern/js/latest/examples.htm#th2_colz

Just open browser console (Ctrl+Shift+I) and type there:

`d3.version`

For me it returns `5.7.0`
