### ISSUE TITLE
JSROOT.TFile() always appends ?stamp= to the generated GET requests

### ISSUE THREAD

**Issue by avivace** [root-project/jsroot#200]
`JSROOT.TFile(endpoint)` with `endpoint being a remote resource, always appends ?stamp= to generated GET requests.

JSROOT.nocache is set as the default and not touched so I'm not sure why this is happening

This is fix-able by appending a "-" in the file name, but is this the expected (default) behaviour?

**Comment by linev** [comment]
`JSROOT.nocache` parameter used for loading JSROOT scripts, but not ROOT files.

Appending `?stamp=xyz` to file name is default behavior to avoid possible confusion with browser cache when reading ROOT files

**Comment by avivace** [comment]
Makes sense. Thanks for clearing that up!
