### ISSUE TITLE
jsroot node basic example not working

### ISSUE THREAD

**Issue by aphecetche** [root-project/jsroot#202]
Hi there,

I'm probably doing something (really) stupid, but I can't get some [basic example](https://root.cern/js/latest/api.htm#node_js_create_svg_src) to work.

What I'm doing : 

```
npm init -y
npm install jsroot
copy and paste code from https://root.cern/js/latest/api.htm#node_js_create_svg_src into first.js
node first.js
```

The result is : 

```
~/tmp/testjsroot$ node --version
v12.18.1
~/tmp/testjsroot$ node first.js
JSROOT version 5.9.0 9/10/2020
load scripts/rawinflate.min.js
load scripts/JSRootIOEvolution.js
/Users/laurent/tmp/testjsroot/first.js:12
  .then((file) => file.ReadObject("hpxpy;1"))
  ^

TypeError: Cannot read property 'then' of undefined
    at Object.<anonymous> (/Users/laurent/tmp/testjsroot/first.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

If I'm trying with the non-promise version it works though : 

```
~/tmp/testjsroot$ curl https://root.cern/js/latest/demo/node/makesvg.js >| test.js && node test.js
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   551  100   551    0     0   5565      0 --:--:-- --:--:-- --:--:--  5565
JSROOT version 5.9.0 9/10/2020
load scripts/rawinflate.min.js
load scripts/JSRootIOEvolution.js
load scripts/d3.min.js
load scripts/JSRootPainter.js
Reuse existing d3.js 5.16.0, expected 5.7.0
load scripts/JSRootPainter.v6.js
load scripts/JSRootPainter.hist.js
load scripts/three.min.js
load scripts/three.extra.min.js
load scripts/JSRoot3DPainter.js
load scripts/JSRootPainter.hist3d.js
THREE.SVGRenderer 102
First render tm = 75
SVG size 253859
```

**Comment by linev** [comment]
Sorry, you are trying to use example from master branch with jsroot version 5.9.0
But code in the master is `6.0 beta` version with significant API changes - 
for instance use of `Promise` class for async operations.
You either should use examples from [5.9 branch](https://github.com/root-project/jsroot/tree/5.9) or use jsroot from git repository.

**Comment by aphecetche** [comment]
ah, indeed, silly me. Sorry.
Is there a timeline for the actual release of 6.0  ? Just to know if I should "just wait and start using v6" or if I should start now with 5.9.
Anyway, thanks,

**Comment by linev** [comment]
> Is there a timeline for the actual release of 6.0

end of November, begin of December.
95% of public interfaces are fixed now, but still some cleanup is necessary

**Comment by aphecetche** [comment]
Thanks. One last question if I may : will 6.0 include Typescript type definitions by any chance ?

**Comment by linev** [comment]
>  will 6.0 include Typescript type definitions by any chance

I have no experience with type definitions. 
Probably, one can provide short file for ~20 main JSROOT functions,
but does it make sense?

**Comment by DraTeots** [comment]
That would help A LOT!

**Comment by linev** [comment]
As I said - I have no experience with it.
Is it only for `node.js` or also relevant for use in web browsers?
Can you propose a draft of it?

**Comment by linev** [comment]
I closing issue - JSROOT v6 was released.
If you want to have `Typescript type definitions` file, 
please open new issue and provide example - I found some examples with modules, 
but JSROOT v6 do not use modules yet
