### ISSUE TITLE
Display of VGM geometry file fails

### ISSUE THREAD

**Issue by f9daq** [root-project/jsroot#204]
When trying to display the Geant4 VGM coverted geometry, an error is raised (it works in ROOT without any problems).

[https://root.cern.ch/js/latest/?gui&file=https://belle2.ijs.si/geom/Belle2Geo.root&item=VGM%20Root%20geometry;1](https://root.cern.ch/js/latest/?gui&file=https://belle2.ijs.si/geom/Belle2Geo.root&item=VGM%20Root%20geometry;1)

JSRootIOEvolution.min.js:17 Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getInt16 (<anonymous>)
    at k.ntoi2 (JSRootIOEvolution.min.js:17)
    at Object.d.IO.ReadMapElement [as readelem] (JSRootIOEvolution.min.js:100)
    at JSRootIOEvolution.min.js:68
    at k.ReadNdimArray (JSRootIOEvolution.min.js:22)
    at Object.a.readelem.c.$fictional.a.func (JSRootIOEvolution.min.js:68)
    at k.ClassStreamer (JSRootIOEvolution.min.js:27)
    at JSRootIOEvolution.min.js:39
    at JSRootIOEvolution.min.js:38
    at XMLHttpRequest.l (JSRootIOEvolution.min.js:32)

Cheers, Rok

**Comment by linev** [comment]
Hi Rok,

Seems to be, it is problem in I/O implementation for std::map<>, which is used inside TGeoManager.
I will investigating it.

**Comment by linev** [comment]
I fix problem in master and 5.9 branch. 
Now it mostly work:

https://jsroot.gsi.de/dev/?file=https://belle2.ijs.si/geom/Belle2Geo.root&item=VGM%20Root%20geometry;1

**Comment by linev** [comment]
I closing issue, it fixed in latest released version

**Comment by linev** [comment]
Sorry, 5.9.1 is not yet released, but 6.0.0 coming very soon
