### ISSUE TITLE
Marker style 2 does not work with 3D plots

### ISSUE THREAD

**Issue by linev** [root-project/jsroot#205]
For that ever reason this marker (+) cannot be converted???
At the same time all other markers are fine.

**Comment by bellenot** [comment]
And what about style 5 ( x ) ?

**Comment by linev** [comment]
I test style 3 (which is *) - it works. But only vertical plus horizontal line fails - no idea why. Maybe style 5 also has a problem

**Comment by linev** [comment]
Main problem was too small width of markers.
Also image size 70x70 was tick to large - one should use power of 2, otherwise three.js have to rescale image
Now all markers are working and also node.js is now supported
