### ISSUE TITLE
displaying TEveGeoShapeExtract  with jsroot fails

### ISSUE THREAD

**Issue by f9daq** [root-project/jsroot#206]
When trying to display the geometry https://belle2.ijs.si/geom/ARICH_extract.root
in ROOT  with 
https://github.com/root-project/root/blob/master/tutorials/eve/show_extract.C
I get the expected result 
![ARICH_extract](https://user-images.githubusercontent.com/23075448/105711891-6ea41400-5f19-11eb-8ca0-430f4bd8a496.png)

when trying to load it via jsroot, I get strange distribution of objects 
https://root.cern.ch/js/latest/?gui&file=https://belle2.ijs.si/geom/ARICH_extract.root&item=Extract

![ARICH_extract_jsroot](https://user-images.githubusercontent.com/23075448/105711892-6f3caa80-5f19-11eb-8dd6-662267f7a064.png)

Is this related to #204 ?
Best regards, Rok

**Comment by linev** [comment]
No, it does not related to issue 204 - it is about I/O problem.
I will check geometry and let you know

**Comment by linev** [comment]
Yes, you are right - it is error with interpretation of matrix values from EVE classes.
In normal `TGeoManager` node matrix defines transformation relative to parent object,
but in EVE classes matrix always contain **world** coordinates and does not depends on parents.

Error was there from very first version of JSROOT code with TGeo classes support,
but nobody was really testing it with TEveGeoShapeExtract.
Thanks to point it out!
I will fix dev version and branch 6. Not sure if I can port it back to 5.9 version

**Comment by linev** [comment]
Now dev version looks like this:

https://jsroot.gsi.de/dev/?file=https://belle2.ijs.si/geom/ARICH_extract.root&item=Extract/ARICH.masterVolume_1&opt=dpnt

![geometry](https://user-images.githubusercontent.com/4936580/105731713-f9900900-5f2f-11eb-8ae2-49d4c2d9b8a8.png)

You can take `dev` version from repository or from https://jsroot.gsi.de/ website

**Comment by linev** [comment]
One remark - while here many semi-transparent volumes present, one need to specify algorithm how rendering order is defined.
I add **dpnt** to draw options, but it is not always provide good results.
You can read [here](https://github.com/root-project/jsroot/blob/master/docs/JSROOT.md#geometry-viewer) about existing algorithms.

**Comment by f9daq** [comment]
Thank you for promptly solving this bug. 

How can I make the top volume invisible?
https://jsroot.gsi.de/dev/?gui&file=https://belle2.ijs.si/masterclass-dev/BelleII_geometry_extract.root&item=Extract&opt=dpnt
Best Regards, Rok

**Comment by linev** [comment]
Unfortunately there is no option to disable top volume drawing - you need to specify item inside it as I did in example URL

**Comment by linev** [comment]
Of course, you can change rendering flag in `TEveGeoShapeExtract` in ROOT file
