### ISSUE TITLE
Cannot read local file (under node) ? 

### ISSUE THREAD

**Issue by aphecetche** [root-project/jsroot#208]
I'm trying to do a very basic thing, opening a file : 
 
```
cat index.js
const jsroot = require("jsroot");

console.log("JSROOT version", jsroot.version);

jsroot
  //.openFile("https://root.cern.ch/js/files/hsimple.root") // WORKS
  .openFile("file://hsimple.root") // DOES NOT WORK
  .then((file) => console.log(file))
  .catch((err) => console.log("boum",err));
```

`node index.js` works if the file is remote but for the local case I get : 

```
JSROOT version 6.0.0 14/01/2021
boum ReferenceError: filename is not defined
    at /Users/laurent/gitlab.cern.ch/alice-muon/testjsroot/node_modules/jsroot/scripts/JSRoot.io.js:2435:23
    at new Promise (<anonymous>)
    at TNodejsFile._open (/Users/laurent/gitlab.cern.ch/alice-muon/testjsroot/node_modules/jsroot/scripts/JSRoot.io.js:2434:14)
    at Object.JSROOT.openFile (/Users/laurent/gitlab.cern.ch/alice-muon/testjsroot/node_modules/jsroot/scripts/JSRoot.io.js:3113:19)
    at /Users/laurent/gitlab.cern.ch/alice-muon/testjsroot/node_modules/jsroot/scripts/JSRoot.core.js:1340:53
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

what am I missing :wink: ?

**Comment by linev** [comment]
Yes, you are right - I did not test local files reading for a while.
There are several problems, I will try to fix them soon

**Comment by linev** [comment]
Should be fixed in `master` and `6.0` branches.

**Comment by aphecetche** [comment]
@linev thanks, that was fast ! How can I test locally ? So far I went the easy route and used `npm install jsroot` but I guess your fixes are not yet published in npm (just guessing, have no idea how deployment to npm is done...)

**Comment by linev** [comment]
Most easy way - checkout jsroot and `dev` branch locally. And in `package.json` provide:
```
 "dependencies": {
    "jsroot": "file:../path/to/jsroot"
  }
```

**Comment by AlbertoPdRF** [comment]
I just stumbed with this same problem. Are there any plans to release a version which includes this bug fix soon?

**Comment by linev** [comment]
I will provide 6.0.1 tag today or tomorrow. 
Next 6.1 version with `TRatioPlot` support will be released in next 2-3 weeks.

**Comment by AlbertoPdRF** [comment]
That's awesome, thanks for the fast reply! 😊

**Comment by linev** [comment]
It is published now in https://github.com/root-project/jsroot/releases/tag/6.0.1 release

**Comment by AlbertoPdRF** [comment]
Works wonderfully, thanks! 🚀
