### ISSUE TITLE
Histogram on canvas displayed with incorrectly zoomed y-axis range.

### ISSUE THREAD

**Issue by mlawe** [root-project/jsroot#209]
As part of the online monitoring for our experiment we display a number of canvases with jsroot drawn from a root file that is frequently updated.

One of the canvases contains a histogram with a restricted y-axis range. When initially displayed the restricted y-axis range is not shown, but instead the range 0 -> 1. It is possible to unzoom the frame to get the correct y-axis range to display, but I assume the initial failure to correctly display the histogram is a bug, as when viewing the canvas within a standard root session the correct y-axis range is displayed.

Initially drawn histogram:
![Screenshot 2021-03-12 at 16 22 57](https://user-images.githubusercontent.com/12392954/111990592-501e5b80-8b0b-11eb-925b-4322023b5919.png)

Correctly displayed histogram after unzooming the y-axis:
![Screenshot 2021-03-12 at 16 23 12](https://user-images.githubusercontent.com/12392954/111990745-7a701900-8b0b-11eb-8588-e6d7ceba73ba.png)

An example root file containing the relevant canvas ("NumSpill") can be found [here](http://hep.lancs.ac.uk/~mlawe/temp/oma_beamspill.root).

**Comment by linev** [comment]
Hi,

Problem is sub-pad, which used to draw histogram. One can see all data members of this sub-pad here:

https://jsroot.gsi.de/latest/?file=../files/tmp/oma_beamspill.root&expand=NumSpill/NumSpillpad&item=NumSpill/NumSpillpad&opt=inspect

One can see selected Y-axis range: `Y1 = -0.13`, `Y2 = 1.18`.
Seems to be, TCanvas and sub-pad were drawn once when histogram created and was empty.
When histogram changed (new bin content is accumulated), painting not performed again and min/max values remain the same.
JSROOT just display that specified in the sub-pad.

There are two possible solution.
1. Call `c->Modified(); c->Update();` before saving canvas in the file. In such case canvas will be redrawn again and expected values will be set.
2. Store histogram directly in the file and display it as is in JSROOT. In such case wired axes range in pad will not affect drawing. It also can be done from existing file:
 
https://jsroot.gsi.de/latest/?file=../files/tmp/oma_beamspill.root&expand=NumSpill/NumSpillpad&item=NumSpill/NumSpillpad/NumSpill

**Comment by mlawe** [comment]
I see, thank you very much for taking the time to understand this, we'll look to change our procedure then. I'll close the issue.
