### ISSUE TITLE
Reading root file from binary content via cockpit

### ISSUE THREAD

**Issue by mvala** [root-project/jsroot#215]
I would like to ask for help. I would like to use https://cockpit-project.org/guide/latest/cockpit-file.html . Mainly watch function
```
file.watch((content, tag, [error]) => { })
```
So after this function is called i have `content` of the file already. How do i fill TFile object from it? In other words How do i do `JSROOT.openFile` without http request. 

Thanks for help

**Comment by linev** [comment]
See https://root.cern/js/latest/jsdoc/JSROOT.html#.openFile

You need to create `ArrayBuffer` istance and provide as argument

**Comment by mvala** [comment]
Perfect it is working when i do
```
JSROOT.openFile(content.buffer)
```
Thanks for support

**Comment by linev** [comment]
Grate!

I create this feature while debugging some other problem.

**Comment by mvala** [comment]
Thanks for you hard work. You are doing great
