### ISSUE TITLE
Provide different way to input value instead of prompt

### ISSUE THREAD

**Issue by linev** [root-project/jsroot#216]
Could help to solve https://github.com/AlbertoPdRF/root-file-viewer/issues/6

**Comment by linev** [comment]
Seems to be, one can use modal forms

https://jqueryui.com/dialog/#modal-form

Moreover, it is also can be applied for TWebCanvas without openui5

**Comment by linev** [comment]
Now jquery dialog class is used to input values.
`prompt` left in few places, which will be removed later

**Comment by AlbertoPdRF** [comment]
That's awesome @linev, thanks a lot for this! Do you plan to include these changes (and the re-binning ones from #210) in a release?

**Comment by linev** [comment]
Yes, in next deys I plan to make 6.1.0 release

**Comment by AlbertoPdRF** [comment]
Great, thanks! :tada:
