### ISSUE TITLE
orthographic projection for geometry viewer

### ISSUE THREAD

**Issue by c-dilks** [root-project/jsroot#217]
Is there a way to view an orthographic projection in the geometry viewer? I couldn't find mention of projection settings in the documentation or the viewer controls. The default projection has parallax, and although it's more realistic, it makes it difficult to tell if objects are really lined up.

**Comment by linev** [comment]
Yes, it is none-documented feature. You only can activate orthographic camera via draw options:

* ortho_camera: https://root.cern/js/latest/?nobrowser&file=../files/geom/rootgeom.root&item=simple1;1&opt=ortho_camera
* ortho_camera_rotate: https://root.cern/js/latest/?nobrowser&file=../files/geom/rootgeom.root&item=simple1;1&opt=ortho_camera_rotate

I need to mention them in documentation,

**Comment by c-dilks** [comment]
Thanks. Could this setting be added to the draw controls box too?

**Comment by linev** [comment]
I add switch in "Advanced" section of control GUI.

https://jsroot.gsi.de/dev/?nobrowser&file=../files/geom/rootgeom.root&item=simple1;1&opt=ctrl

**Comment by c-dilks** [comment]
Very nice, thanks for doing this so quickly!
