### ISSUE TITLE
Some Multigraph entries invisible in SimpleGUI

### ISSUE THREAD

**Issue by akveton** [root-project/jsroot#218]
Hello,

I have a TMultiGraph being drawn with the AlcP options.

Today, by chance, I noticed that when opening the same plot in desktop root and the jsroot SimpleGUI, some points are invisible - they are mouseoverable, but they are not drawn, nor line-connected.

Here is an example of the plot being opened in the jsroot gui:

![image](https://user-images.githubusercontent.com/17496922/127013295-efc18c73-d1ce-4fa6-a626-146420d6b7c9.png)

Feeding the same file into desktop root however, I get this:

![image](https://user-images.githubusercontent.com/17496922/127013654-6d50c7e9-9a55-49be-906c-5276885699c4.png)

As I mentioned, I noticed that the points are there, but just not drawn, here is an example of one:

![image](https://user-images.githubusercontent.com/17496922/127013796-36f18142-7a73-4666-a56b-6f5ebe6bfb89.png)

I have discovered this in a rather old version (5.5.x 20/08/2018). However, I have upgraded to the latest version afterwards (dev 16/07/2021) and I still see the problem (although it is considerably harder to mouseover the points there, so I was not able to verify their (invisible) presence in the latest version.

Is there maybe some limit of points being hit that causes them to be optimized away or so? The number of points in the concerned plot is 58066.

Thanks for your assistance.

**Comment by linev** [comment]
Can you attach ROOT file?

**Comment by akveton** [comment]
Hello, here it is zipped. It is the exact same file that I used for the example.

[Multigraph_issue_example.zip](https://github.com/root-project/jsroot/files/6886289/Multigraph_issue_example.zip)

**Comment by linev** [comment]
Thanks for example.

Seems to be `"lcP"` draw option handled differently by ROOT and JSROOT. ROOT draws both `line` and `curve`, while JSROOT either `curve` or `line`. I will check this and fix in JSROOT.

Second - there is really limitation for 5000 bins which can be draw with `curve` option. 
If there are much points, some of them will be skipped - as in your case. 

And third - `curve` drawing has strange inprecision. Marker positions do not match with curve ones.
I need to fix this error as well.

**Comment by linev** [comment]
Main problems should be solved now in JSROOT master.
Now, when `"lcP"` option is specified, line and curve will be drawn.
Precision lost problem also should be solved with `curve` drawing.
I increase limit from 5000 to 20000 points which are drawn in `curve` mode.
If there are more points - only every N-th point will be taken from the `TGraph` for drawing.

**Comment by akveton** [comment]
Thank you for the information. Is there a plot option that does not have this bin limitation?

**Comment by linev** [comment]
> Is there a plot option that does not have this bin limitation?

I add "cc" option - it will force all points to be displayed in the `curve` mode

**Comment by akveton** [comment]
Thank you. One more question - does the `line` mode have any limitation, or was this unique to the `curve` mode?

**Comment by linev** [comment]
No, `line` draw all points

**Comment by akveton** [comment]
Ok, thank you very much!
