### ISSUE TITLE
event listerner very slow

### ISSUE THREAD

**Issue by JensInc** [root-project/jsroot#219]
I am successfully requesting data from a `THttpServer` via:
```
  <script type='text/javascript'>
    JSROOT.httpRequest("https://subdomain.domain.xx/root/Objects/subfolder/histo/root.json", 'object')
             .then(obj => {
       var histo = JSROOT.parse(obj);
       histo.fName = "2D";
       JSROOT.redraw('object_draw', histo, "lego2");
       console.log(obj)
    })
  </script>
```
Compared to the example on the root.js webpage this is very slow. E.g. event handling for zoom takes ~350 ms. 

Am I doing anything wrong. Unfortunately I have not found example for drawing AND data request. In the examples the data object is always already existing.

**Comment by linev** [comment]
There could be several reasons.
Either server responses too slow or histogram is very large and drawing takes too long.
Can you open in browser network profiler to see how long network request takes?

**Comment by linev** [comment]
Did you check size of the histogram?
That are number of bins?

And sorry for the long delay - I had long vacations

**Comment by JensInc** [comment]
It has been less than 10000 bins (TH2I with 320 x 320 bins).

Now I have tested with 10 x 10 bins and it is fast.

Are there any limitation? For the 320 x 320 bins I cannot see any limitation by CPU, IO or bandwidth.

**Comment by linev** [comment]
320 x 320 bins is relatively big histogram for lego plots. 
It works, but not as performant.
Just try same histogram with "colz" option - to exclude any possible network or browser side effects.

**Comment by JensInc** [comment]
Unfortunality it has been the purpose to use a 3D view like "lego". I guess there are no options in software or hardware to speed it up. (?) And also I guess that using the python wrapper in the backend has no significant effect to performance  - has it?. 

Even using "colz" with all bins filled is slow in zooming with 320 x 320 pixels. ("lego2" with all 320 x 320 pixels filled takes more than 10 s to load and is nearly totally frozen. Using the desktop version even in python it is fast.)

The [example](https://root.cern/js/latest/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=lego2fb) with 40 x 40 pixels is still fast. And even complex plots [like](https://root.cern/js/latest/?nobrowser&file=https://root.cern/files/cms.root&item=cms;1&opt=macro:https://root.cern/files/cms_cmse.C;clipxyz) are fast in rotation. 

For interactive 3D plots at desktop and web version ROOT is much better than mathplotlib - [there](https://github.com/matplotlib/matplotlib/blob/master/examples/mplot3d/hist3d.py) one can just rotate but not zoom.

**Comment by linev** [comment]
> Even using "colz" with all bins filled is slow in zooming with 320 x 320 pixels.

It is strange. 2D drawing should be fast, histogram with [200x200](https://root.cern/js/latest/examples.htm?more#th2_logx) bins works very fast for me. Probably, loading of histogram takes too much time?

If you really need 3D plot - try to use [lego](https://root.cern/js/latest/examples.htm#th2_lego) or [lego1](https://root.cern/js/latest/examples.htm#th2_lego1) draw options. They should be rendered faster then [lego2](https://root.cern/js/latest/examples.htm#th2_lego2).

If necessary to color histogram levels, use `lego4` draw option.
It is faster then `lego2` while avoids line drawings. 
Here is [200x200 bins lego4](https://jsroot.gsi.de/dev/?nobrowser&file=../files/QAresults.root&item=PIDqa/PIDqa1/ITS/hNsigmaP_ITS_electron;1&opt=lego4,logx), which works reasonable for me. Zooming with latency of ~0.5 sec.

**Comment by linev** [comment]
>  And even complex plots like are fast in rotation.

Rotation does not involve complex code in JavaScript - it is handled by WebGL in graphics card. 
Therefore even complex 3D plots works reasonable.

But histogram zooming requires recalculation of all vertices in JavaScript and for 320x320 bins histogram there are many of them.

**Comment by JensInc** [comment]
* For `lego2` the loading of histogram takes actually a long time - but this is not a problem for me. 
* `lego`, `lego1` and `lego4` are also OK - but `lego2` looks better.
*  zooming in `lego4` now also with 200x200 pixels take much more than 10 s for me. 
 ```
class Th2Maker():
    def __init__(self):
       self.__serv = ROOT.THttpServer("http:8080")
       self.__serv.CreateServerThread()
       self.__histo = ROOT.TH2I('h1', '', 
                                self.__X_BIN_MAX, 0, self.__X_BIN_MAX,
                                self.__Y_BIN_MAX, 0, self.__Y_BIN_MAX)
       self.__histo.SetName("histo")
       for x in range(0, self.__X_BIN_MAX):
           for y in range(0, self.__Y_BIN_MAX):
               self.__histo.SetBinContent(x, y, x+y)
       self.__serv.Register("subfolder", self.__histo)
       hpx = Hpx()
       self.__serv.RegisterCommand('/test', '/hpx/.notify(arg1%,\'arg2%\')')

    __X_BIN_MAX: Final = 200
    __Y_BIN_MAX: Final = 200 
```
*  OK: For rotation the reason should be related to my client configuration.

**Comment by linev** [comment]
I tried same kind of macro with standard ROOT shell:
```
void lego()
{
   THttpServer* serv = new THttpServer("http:8080");
   serv->CreateServerThread();
   const int nbinsx = 200, nbinsy = 200;

   auto histo = new TH2I("histo","TH2I title", nbinsx, 0, nbinsx, nbinsy, 0, nbinsy);

   for (int i=0;i<nbinsx;i++)
      for (int j=0;j<nbinsy;j++)
         histo->SetBinContent(i+1,j+1,i+j);
}
```
I see that in Chrome zooming works faster than in Firefox.

**Comment by JensInc** [comment]
Indeed, Chrome/ium is much faster. Even for the `lego2` version the zooming is OK when using  middle mouse button and mouse movement. (When using mouse wheel it is much slower.) Also the rotation is fast for me. 

Thank you very much. 

P.S.: It seems that I can use it - after [managing passing parameters.](https://stackoverflow.com/questions/68707792/root-js-how-to-pass-parameters-to-thttpserver)
