### ISSUE TITLE
TCutG for TH2

### ISSUE THREAD

**Issue by matLogh** [root-project/jsroot#220]
Hi!
I am just discovering the jsROOT and I wonder if there is possibility to implement following functionality: I would like to plot a TH2 in the browser, create a TCutG on given TH2 and send it back to the server. Is it possible to do something like this now?

thank you!
matus

**Comment by linev** [comment]
Hi Matus,

>  Is it possible to do something like this now?

Not really. Default JSROOT interface let display existing objects from running THttpServer.
But it is not possible to create new objects and not allowed to modify objects on server side.

One could do this (with some limitations), but it will require to implement some custom code on JavaScript side.

Regards,
Sergey

**Comment by matLogh** [comment]
Thank you!
