### ISSUE TITLE
What is the structure of the root file

### ISSUE THREAD

**Issue by ED-97** [root-project/jsroot#221]

**Comment by linev** [comment]
Can you describe which kind of information you need?
Some generic information you can find in [TFile](https://root.cern/doc/master/classTFile.html) class docu.

**Comment by ED-97** [comment]
For example, In a binary class file,information structure of detector, their parent-child relationship and material related information .Can you give me a general description

**Comment by linev** [comment]
To create ROOT binary file, one have to use ROOT framework.
Content of ROOT binary file build based on C++ classes, using ROOT I/O - and can be extremely complex.

ROOT I/O also supports JSON output.
Here is example of geometry as JSON: https://root.cern/js/files/geom/evegeoshape.json.gz
And how it can be displayed by **jsroot**: https://root.cern/js/latest/?nobrowser&json=../files/geom/evegeoshape.json.gz

**Comment by ED-97** [comment]
Q1. In parent-child nodes, JSON files can be nested to preserve the relationship between nodes. Is the same true for binary files?  
Q2. Is material information in binaries followed by nodes, and each node has a separate record?

**Comment by linev** [comment]
> Q1. In parent-child nodes, JSON files can be nested to preserve the relationship between nodes. Is the same true for binary files?

Structure of binary and JSON files fully reflect structure of C++ classes. In this particular case - [TGeoNode](https://root.cern/doc/master/classTGeoNode.html) and [TGeoVolume](https://root.cern/doc/master/classTGeoVolume.html).
Normally geometry instances organized together by [TGeoManager](https://root.cern/doc/master/classTGeoManager.html) class.

> Q2. Is material information in binaries followed by nodes, and each node has a separate record?

Any C++ object stored into binary or JSON file first time its reference appears. If same object appears next time - only its reference will be written. In case of JSON one could see them like `{ "$ref": 55 }`.

I really recommend to read ROOT C++ classes documentation to understand how TGeo classes are organized - and use them to create ROOT files which can be displayed by jsroot. I see no chance that such files can be created directly - there are too many details.

**Comment by ED-97** [comment]
Ok, thank you very much for your explanation, you did a great job  
Does the system support fuzzy search now?For example, select certain types of nodes based on their name prefixes.
In addition, property changes are now made globally,Can I change the color and opacity of a node,And save it to a file.

**Comment by linev** [comment]
> Does the system support fuzzy search now?

You can use different methods to iterate over TGeo nodes.
For instance - [TGeoIterator](https://root.cern.ch/doc/master/classTGeoIterator.html) class.

But I recommend to ask such questions on [ROOT forum](https://root-forum.cern.ch) where you find more experts in the topic.
