### ISSUE TITLE
Disabling dragging the plot

### ISSUE THREAD

**Issue by piotrpolec** [root-project/jsroot#224]
I'm using JSROOT in a project and dragging of the plot proved to be quite unintuitive and irritating. I found this https://root-forum.cern.ch/t/jsroot-multigraph-dragging-around-plots/39595, but I think there could be two things improved here:

- I haven't found anything about the `InvertBit` method in JSROOT documentation, is it on purpose? If I haven't found this issue on forum, there would have been no way for me to find out about the solution of this. I found it later in the ROOT documentation, but I'm not a ROOT user.
- What do you think about creating a wrapper for it, something along the lines `graph.fDisableEditing`?

**Comment by linev** [comment]
Hi,

It depends where `TGraph` object is created. If it is C++, just call [TGraph::SetEditable()](https://root.cern.ch/doc/v624/classTGraph.html#af1e737a05c090108f9d81991e184cd4c) method. Like `gr->SetEditable(false);`

If `TGraph` object created directly in JSROOT, just do `gr.InvertBit(JSROOT.BIT(18));`
Methods `InvertBit()` and `TestBit()` automatically assigned to all TObject-derived classes.
Unfortunately, these methods are not mentioned in [reference](https://root.cern/js/latest/jsdoc/JSROOT.html) - as well as few others for histograms, graphs and axes.

I could add some flag to [JSROOT.settings](https://root.cern/js/latest/jsdoc/JSROOT.settings.html) to completely disable editing mode for `TGraphs`

**Comment by piotrpolec** [comment]
The TGraph is created directly in JSROOT as shown below
`const tgraph = JSROOT.createTGraph(dataSeries.y.length, dataSeries.x, dataSeries.y)`
For now I resort to `InvertBit` as you suggested, but I think the flag in JSROOT.settings would be helpful :+1:

**Comment by linev** [comment]
Now with master branch one could specify: `JSROOT.settings.DragGraphs = false`

**Comment by grzanka** [comment]
@linev is this feature also deployed to `https://root.cern.ch/js/latest/scripts/JSRoot.core.js` ?

**Comment by linev** [comment]
> is this feature also deployed to https://root.cern.ch/js/latest/scripts/JSRoot.core.js

Not yet - this feature implemented in `master` branch. 
You can use it from https://jsroot.gsi.de/dev/scripts/JSRoot.core.js - root.cern site will be updated later.

`latest` points to latest stable release - currently 6.3.2
