### ISSUE TITLE
Changing Y axis limits for TGraph

### ISSUE THREAD

**Issue by grzanka** [root-project/jsroot#226]
I'd like to adjust manually Y-axis limits for a TGraph.

As suggested in https://github.com/root-project/jsroot/issues/225 I started to use a TH1F histogram associated to TGraph to manipulate axis labels.

It seems however that changing axis limits for underlying histogram (i.e. `fYaxis.fXmin`  and `fYaxis.fXmax`) has no effect on the overall plot. You can take a look at the minimum code to reproduce here:

https://jsfiddle.net/grzanka/xg4qauh1/23/

By looking at the code suggested in https://github.com/root-project/jsroot/issues/225#issuecomment-1002239180  I've discovered that using `fMinimum` and `fMaximum` attributed of TGraph does the job.

Which is the desired way of adjusting the limits ?

**Comment by linev** [comment]
To change Y axis limits of `TGraph`, one should use `fMinumum` and `fMaximum` members.

**Comment by grzanka** [comment]
> To change Y axis limits of `TGraph`, one should use `fMinumum` and `fMaximum` members.

Thanks for clarification!
