### ISSUE TITLE
Question: Using JSROOT and THttpServer to view ROOT files on GitHub?

### ISSUE THREAD

**Issue by fanurs** [root-project/jsroot#230]
Dear authors,

I have been using JSROOT and THttpServer to look at ROOT files from my local server with very good experience.

I wonder if it would be possible to use them to look at ROOT files on the internet, e.g. ROOT files that were committed to GitHub repos?

Here is one specific example that I'm looking at: https://github.com/nscl-hira/E15190-Unified-Analysis-Framework/blob/master/calibrations/MB_HitCondition_140AMeV.root

Regards,
Fanurs

**Comment by linev** [comment]
Hi Fanurs,

Unfortunately, github does not provide plain HTTP access to files in repositories.
There was [rawgit.com](https://rawgit.com/), but it is no longer working.
You could try to use `github.io` pages - there you can put any kind of files, including ROOT. 

I create example on my pages - see [repository](https://github.com/linev/linev.github.io/tree/master/hsimple) and how it works:
http://localhost:8000/github.io/hsimple/?file=hsimple.root&item=hpx

Regards,
Sergey

**Comment by fanurs** [comment]
@linev Thanks for the quick response. Github Pages would be a good alternative solution too.

Have a nice day,
Fanurs

**Comment by AlbertoPdRF** [comment]
Hi @fanurs!

I'm replying to let you know that there's now another way of viewing ROOT Files hosted on a GitHub's repository:

1. Open your repository on a [web editor](https://github.dev/github/dev) (i.e. press `.` when browsing your repository)
2. Install the [ROOT File Viewer extension](https://marketplace.visualstudio.com/items?itemName=albertopdrf.root-file-viewer) (this is just necessary the first time)
3. Browse your ROOT Files freely!

**Comment by fanurs** [comment]
Hi @AlbertoPdRF!

Wow, thanks a lot! I have been using the extension on VS Code, and I am also aware of the web editor. But I had never thought of combining both technologies.

BTW, I really appreciate your effort in maintaining the extension. It has been boosting my productivity a lot.
