### ISSUE TITLE
How to get the information in the prompt box when using jsroot

### ISSUE THREAD

**Issue by zhangsh0327** [root-project/jsroot#231]
Recently, I met a question. When I want to embed the histogram implemented with jsroot into my web page, I want to get the information in the prompt box, and click the corresponding bin to jump to other pages. But by looking at the official website, I didn't find how to do it.

**Comment by linev** [comment]
See example with custom tooltip handler:

https://root.cern/js/latest/api.htm#custom_html_tooltip_hanlder

https://root.cern/js/latest/api.htm#custom_html_tooltip_hanlder_src

One can have custom handler for click, double click or just for tooltip action.

**Comment by linev** [comment]
And another alternative - add custom items into context menu:

https://root.cern/js/latest/api.htm#custom_html_context_menu

https://root.cern/js/latest/api.htm#custom_html_context_menu_src

In example context menu entry produced from bin index or bin text at which context menu was activated.
One can add any kind of action into that menu - including opening another web page.

One important remark - very soon new JSROOT version will be released.
It uses ES6 modules and API is changed. You can check code here:

https://root.cern/js/dev/api.htm#custom_html_context_menu_src

**Comment by linev** [comment]
I hope, you get information you need.
And I recommend to use new `7.0` version
