### ISSUE TITLE
Display data from .json file via iframe

### ISSUE THREAD

**Issue by MarenStratmann** [root-project/jsroot#234]
Hi,
I want to display histograms in a react app with jsroot. I downloaded jsroot, host it on my local server, and integrate it into my react app using an iframe. 
Now the issue is that I cannot display histograms that are stored in json format (converted via TBufferJSON::ConvertToJSON). My iframe looks like this:
` <iframe src='http://localhost:5012/jsroot/index.htm?json=http://localhost:5012/Result.json&item=occ_FE_175&draw' />` 

Displaying root files in the same manner:
`<iframe src='http://localhost:5012/jsroot/index.htm?file=http://localhost:5012/Result.root&item=occ_FE_175;1&draw' />`
works fine, but I need to display the json files. Is this possible within an iframe?

**Comment by linev** [comment]
One should use simply url like:
```
<iframe src='http://localhost:5012/jsroot/index.htm?json=http://localhost:5012/Result.json' />
```
If necessary, one can provide draw option `&opt=colz`. 
Url parameter `&draw` is not required at all.

**Comment by linev** [comment]
Here you can find more examples with URL parameters:

https://root.cern/js/latest/api.htm#url_syntax_use_json

**Comment by MarenStratmann** [comment]
Hi linev,

> <iframe src='http://localhost:5012/jsroot/index.htm?json=http://localhost:5012/Result.json' />
This worked for me, thank you very much!
