### ISSUE TITLE
Use JSROOT with Webpack on Node.js environment

### ISSUE THREAD

**Issue by AlbertoPdRF** [root-project/jsroot#235]
After #233, I'm trying to improve the [ROOT File Viewer VS Code extension](https://github.com/AlbertoPdRF/root-file-viewer) by bundling it with Webpack. However, I'm having problems using the `HierarchyPainter` as it tries to manipulate the `document`, which is not available on a Node.js environment. This may be because of the configuration needed to get Webpack running in the first place, which I think assumes that it runs in the browser, but it could also very well be because of something else.

My attempt at getting everything working is available [here](https://github.com/AlbertoPdRF/root-file-viewer/commit/5e4f16e11180b8d5817cff5171b85d7fc7ec814a), and the error can be seen by:

1. Opening the base folder with VS Code
2. Installing the recommended extensions
3. Pressing `F5` to compile and run the extension
4. Toggling the developer tools with `Ctrl+Shift+I` in the new window

**Comment by linev** [comment]
Are you using Code on Windows or Linux?
How can I install your plugin from `webpack` branch?

**Comment by linev** [comment]
I come to point:

https://github.com/AlbertoPdRF/root-file-viewer/blob/webpack/src/rootFileEditor.ts#L94

Here `document` is not normal document, 
but `HierarchyPainter` tries to select `#hierarchy` from it.
How it works in that environment - how such element can be found?
`document.getElementById("hierarchy")` does not work.

**Comment by AlbertoPdRF** [comment]
In this environment the normal HTML document is `webviewPanel.webview.html`. I don't know though how JSROOT can get the `#hierarchy` element from it, or if it's possible at all.

**Comment by linev** [comment]
`webviewPanel.webview.html` is just HTML code, not real document.
Seems to be, that HTML code inserted into `<iframe>` element and processed there.
Actually only at that moment `HierarchyPainter` should be created. Kind of:
```
 <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">

        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href="${styleResetUri}" rel="stylesheet" />
        <link href="${styleVSCodeUri}" rel="stylesheet" />
        <link href="${styleMainUri}" rel="stylesheet" />

        <title>ROOT File</title>
      </head>
      <body>
        <div id="hierarchy"></div>

        <script>
          const vscode = acquireVsCodeApi();
          const h = new HierarchyPainter("ROOT File Hierarchy");
          h.no_select = true;
          h.show_overflow = true;
          h.prepareGuiDiv("hierarchy", layout);
          h.createBrowser("browser").then(() => h.openRootFile(document.uri));
          vscode.postMessage({ type: "ready" });
        </script>
      </body>
      </html>`
```
But how one can access all necessary components there - I have no idea.

**Comment by AlbertoPdRF** [comment]
That's actually kind of how the extension is currently working, you can see in the `master` branch how it's done. The problem in that case is that I import the whole JSROOT from the `node_modules` folder, and so I need to keep it in the production version, preventing any bundling.

**Comment by linev** [comment]
But one have to import JSROOT into HTML element - otherwise interactivity will not work.

One can generate SVG and inject pure SVG into HTML. This does not require any JavaScript ROOT import,
but this also means no interactivity.
