### ISSUE TITLE
Updating ROOT files in the browser

### ISSUE THREAD

**Issue by jacobfriedman** [root-project/jsroot#241]
If I'm not mistaken, this library displays ROOT files in a read-only format, correct?

For instance- Is there an option for users to modify the ROOT file in the Browser- and does that modification instantly update to the main display?

Say we want to take a GraphViz tree and modify it in the browser as a direct transformation on the object for rendering-  is it at all possible?

**Comment by linev** [comment]
It is rather ROOT-related question and should be posted in ROOT forum:

https://root-forum.cern.ch/
