### ISSUE TITLE
Support \text in LaTeX

### ISSUE THREAD

**Issue by stephanlachnit** [root-project/jsroot#243]
It looks like jsroot does not support the `\text{}` macro (see e.g. [here](https://bearnok.com/grva/en/knowledge/software/mathjax#fonts)). I check it here:
https://github.com/root-project/jsroot/blob/60880f814fef347b182c996c1b780a1ff359a3c2/modules/base/latex.mjs#L224-L263

**Comment by linev** [comment]
As I can see, `#text` macro does not provided by [`TLatex`](https://root.cern/doc/master/classTLatex.html)
When rendered with MathJax - it should work.

**Comment by stephanlachnit** [comment]
MWE in ROOT:
```C++
auto g = TGraph(1)
g.SetTitle("E_\\text{beam}")
g.Draw()
```

**Comment by linev** [comment]
I see now.

But this is a way how ROOT automatically switches to `TMathText` rendering.
In principle, I can enable same for JSROOT. 
But in both cases `\\text` is not parsed by latex.

**Comment by stephanlachnit** [comment]
>  When rendered with MathJax - it should work.

Do you mean I have to do `JSROOT.settings.Latex = JSROOT.Latex.MathJax`?

>  But in both cases \\text is not parsed by latex.

Isn't TMathText basically Latex?

**Comment by linev** [comment]
> Isn't TMathText basically Latex?

It uses external library in ROOT. In case of JSROOT it is MathJax.

> Do you mean I have to do JSROOT.settings.Latex = JSROOT.Latex.MathJax?

Yes, this enables usage of MathJax - when special symbols like `\` found in the string.

**Comment by stephanlachnit** [comment]
> Yes, this enables usage of MathJax - when special symbols like \ found in the string.

Ok thanks for the help! I will close this then.

**Comment by linev** [comment]
I implement now same way as ROOT does - one `\` symbol is found, `MathJax` is automatically invoked.

https://root.cern/doc/master/classTLatex.html#L14

In the past there were different problems with `MathJax`, but now it works reliably
