### ISSUE TITLE
TH1 tooltips mouse position

### ISSUE THREAD

**Issue by piberger** [root-project/jsroot#248]
Hi,
Is there a way to also show the tooltips for TH1 histograms when the mouse is above the histogram line?
So far only works when the cursor is below the line, which is not optimal for usability in my case when there are low/zero bins.

**Comment by linev** [comment]
Unfortunately it is not possible.

Will require significant change in the logic how tooltips are implemented

**Comment by piberger** [comment]
Ok, thanks for your answer, 

As workaround I'm now drawing a second transparent histogram on top, with all bins set above the maximum of the axis range.
Seems to do the job.

**Comment by linev** [comment]
Yes, it is feasible workaround to get tooltips working.

With current implementation JSROOT does not get mouse events at all when nothing is drawn behind the mouse.
