### ISSUE TITLE
Problem opening file via jsroot

### ISSUE THREAD

**Issue by mvala** [root-project/jsroot#250]
I am not able to open file https://eos.ndmspc.io/eos/ndmspc/scratch/out_directory.root via js root browser. But i can open file from same server https://eos.ndmspc.io/eos/ndmspc/scratch/out_pt.root. 
I can open both file via `TBrowser`

Any hint? Thanks

**Comment by linev** [comment]
Yes, I can reproduce problem.
It is error in decoding of http response with multipart content - which does not appear at all with second file.
I will try to fix it

**Comment by linev** [comment]
Should be fixed now:

https://jsroot.gsi.de/dev/?file=https://eos.ndmspc.io/eos/ndmspc/scratch/out_directory.root

**Comment by mvalarh** [comment]
Thanks

**Comment by mvala** [comment]
Thanks
