### ISSUE TITLE
Loading customized library

### ISSUE THREAD

**Issue by AvencastF** [root-project/jsroot#252]
I'm wondering if jsroot supports loading some self-defined classes as branches in the root file. 
For example, we will define some simple C++ structs/classes to store event information and for reconstruction.

**Comment by linev** [comment]
Normally streamer infos are used to read data from ROOT files.
Only if you have custom streamers for your classes (which is very rare case) you will need special support for these classes in jsroot

**Comment by AvencastF** [comment]
Thanks for the clarification. I tried to load my own root file on the demo page and got errors in the figure. 
The basic structure of my root file is,

A TTree containing one self-defined Event branch and for the Event branch:

- std::map<string, std::vector < self-deinfed class > > collections

So basically they are all STL containers, but some self-defined classes inside, like "particles", "calohits". I can read through python if loading my C++ library. I'm wondering if it's possible to pass the C++ library or the related information to jsroot.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/19330542/224361696-74f4c047-7fc7-4695-983c-e6a56922454b.png">

**Comment by linev** [comment]
Can you provide such file and C++ headers for it?
Seems to be, some complex containers not yet supported by jsroot.

**Comment by AvencastF** [comment]
Sure. But the dependency in my case is complicated. I think it's still not supported. Maybe I should convert the self-defined class to plain data format to jsroot. Thank you so much for answering!

**Comment by linev** [comment]
In JSROOT it is possible to support custom streamers.
It is not very well documented, but can be done.

Like this example:

https://github.com/root-project/jsroot/blob/master/demo/gaudi.js

or

https://github.com/root-project/jsroot/blob/master/demo/amore.js
https://root.cern/js/latest/api.htm#custom_html_user_io

If you can cook down your problem to some small reproducer, then I can try to add support for it.

**Comment by AvencastF** [comment]
Many thanks. This seems to be cool. In my case, it's a little bit hard to make a small data library...I want to write an event display program in JS. So the dependencies are large (for the data file)... I think it will be really lots of work adding such streamers.
