### ISSUE TITLE
Read GeometryManager from ROOT exlcuding dependency on gl

### ISSUE THREAD

**Issue by AvencastF** [root-project/jsroot#253]
Hi, 

jsroot is a fancy lib that allows me to play with TGeoManager. I'm trying to use electron to build a desktop app to display the output from Geant4. The geometry information is saved in TGeoManager and jsroot will read it out and convert it to a three.js object. I appreciate this convenient function. 
When I try to use electron to build the app, there is a problem with gl on windows. I tried several ways and couldn't figure it out. But since I'm only using the "read TGeoManager from root file and export" function. Is it possible to exclude gl at this time and copy several scripts from jsroot to achieve the same functionality? 

I'm new to js and electron, please forgive me if I've asked something stupid. 

Best,
Frank

**Comment by linev** [comment]
Hi Frank,

If I understand correctly, you are trying to use `build()` function from `TGeoManager.mjs` module.
As I can see - it does not use `gl` functionality at all while it does not performs any rendering. 

To my understanding - if you import and use only this function, it should not instantiate `gl` module.

If it helps - I can create special "bundle" which only contains ROOT files I/O and `build` function.
In such bundle `import('gl')`  or `import('canvas')` will not appear at all.
You can get several bundles by running `npm run build` in main directory - but there is no dedicated one for geometry.

Regards,
Sergey

**Comment by AvencastF** [comment]
Hi Sergey,

Many thanks for your help.
Yes, I only need the converted three.js objects (I need to combine them with other inputs in the three.js scene). 
I've tried to import a single function from jsroot but it fails due to some compilation error in my dev app (I will definitely try it today, but now I'm outside so I can't do experiments on it for now.) I really appreciate it if it's possible to make a special bundle with only root file I/O and build functionality. Hope it does not need much work on your side. 

Best,
Frank

**Comment by linev** [comment]
I add special bundle: 

https://github.com/root-project/jsroot/blob/master/modules/geom/bundle.mjs

If running `npm run build`, it will produce `build/geom.js` file.

If necessary, one can add more exports - once you understand better that exactly you needs.

**Comment by AvencastF** [comment]
Many thanks. 

Just want to clarify here. Do I need to go to the `./node_modules/jsroot/` and then `npm run build`?

**Comment by linev** [comment]
While feature available only in repository, you have to clone it on your workspace and run `npm install; npm run build` there. To use such custom build, you can add JSROOT to your `package.json` file as:
```
  "dependencies": {
    "jsroot": "file:../path/to/jsroot",
  }
```

**Comment by AvencastF** [comment]
Thanks. I will try the building app tonight. So the newly-built geom bundle will only affect the electron build stage. If in the dev stage, still keep everything as before?

**Comment by AvencastF** [comment]
Hi Sergey,

I'm not sure if I'm doing it the right way. 

1. `git clone jsroot` and run `npm install; npm run build`
2. `import {openFile, build} from '../../../jsroot/modules/geom/bundle.mjs';` (this won't work)
3. `import {openFile} from 'jsroot/io';
import {build} from 'jsroot/geom';` this works, if I run `npm install --save .\jsroot\`. But in the build stage, it still requires gl library.

How should I only include the functions in bundles?

Best,
Frank

**Comment by linev** [comment]
Hi,

Seems to be,  generated script cannot be directly used by `node.js` - it is rather for web browser use.

You also can try same with normal jsroot like:
```
import { openFile }  from 'jsroot/io';
import { build }  from 'jsroot/geom';
// your code here
```
Maybe it also will work for you.

Regards,
Sergey

**Comment by linev** [comment]
I change `rollup.config.js` script to build ES6 module `geom.mjs`.
You can try it - it should be possible to import such module into node.js.

**Comment by linev** [comment]
But it is just shortcut for solution I explained before.
With plain jsroot you can import methods from `jsroot/io` and `jsroot/geom` sub-modules
