### ISSUE TITLE
One of the dependency: headless-gl install is so slow

### ISSUE THREAD

**Issue by mrceyhun** [root-project/jsroot#261]
Probably it is not the best place to ask but maybe I can learn better ways to install jsroot. I'm trying to install jsroot with `npm i jsroot` however `gl`(headless-gl) dependency installation takes ~10 minutes to install in Mac OS. Do you know any workaround for it?

**Comment by linev** [comment]
It is correct place for `jsroot` questions. 

During `headless-gl` installation several C libraries are compiled. 
And it takes time - on the 64bit linux is about 1 minute. 
Strange, that on Mac platform it is much longer.

Without `headless-gl` no any 3D rendering is possible.

**Comment by mrceyhun** [comment]
Thanks @linev 

If anybody interested, I am sharing the install times for `headless-gl`

**Mac OS 13.4**
```
$ time npm install gl
added 168 packages in 12m

real	11m46.619s
user	7m39.989s
sys	1m15.578s
```

**docker image `node:20`**
```
# after setting python3 as python and installing all required apt packages

root@9c9397c28a57:/app# time npm i gl
added 168 packages in 6m

real	5m35.111s
user	5m16.866s
sys	0m29.779s
```

MacOS install time is not important but install time in node docker image is kind of single blockage for the fast build time. It seems there is nothing I can do to improve it. I am closing the issue since after this point it is more of a `headless-gl` problem.

**Comment by linev** [comment]
May be  it also depends which libraries are already installed on the system and can be reused by `headless-gl`.
For me installation time is: `npm install  107.65s user 22.82s system 101% cpu 2:08.85 total`

**Comment by linev** [comment]
I can provide installation without `headless-gl` - if node only used for creating jsroot builds or just for 2D graphics.

**Comment by mrceyhun** [comment]
Existing packages before npm install are:
```
FROM node:20 as build-stage
# Ref: https://github.com/stackgl/headless-gl#system-dependencies
RUN apt-get update -y && apt-get install -y make gcc g++  build-essential git libxi-dev libglu1-mesa-dev libglew-dev pkg-config mesa-utils xvfb libgl1-mesa-dri libglapi-mesa libosmesa6
RUN ln -s /usr/bin/python3.11 /usr/bin/python
```

I think I don't need 3D graphics, and it would be great to install it without headless-gl.

**Comment by linev** [comment]
You can try `dev` branch.
With `npm install --production`
If it works - I will merge it into master

**Comment by linev** [comment]
I need to add "gl" again to dependencies - starting from JSROOT v 7.7.1
Otherwise one cannot do simple install and import of 'jsroot'. See:

https://root-forum.cern.ch/t/cannot-use-jsroot-in-next-js-react/59493/

Recent "gl" v 8.0.2 provided for several platforms and installation does not take too much time.

**Comment by mrceyhun** [comment]
Fine for me @linev , I've been away of the project since a while...
