### ISSUE TITLE
"Uncaught (in promise) RangeError: offset is outside the bounds of the DataView" in some ALICE objects

### ISSUE THREAD

**Issue by knopers8** [root-project/jsroot#262]
Hello!
I am trying to understand an issue we have with displaying some objects in the ALICE Quality Control GUI. These are [QualityObjects](https://github.com/AliceO2Group/QualityControl/blob/master/Framework/include/QualityControl/QualityObject.h), they inherit TObject. To reproduce the issue, please open `broken_qo.root` in https://jsroot.gsi.de/latest/ and click "Inspect" in `ccdb_object`. It will fail to open it and in the console the following message will appear:
```
Uncaught (in promise) RangeError: offset is outside the bounds of the DataView
```
I was told by @graduta that the issue happens during decompression.

The `broken_qo.root` object works well in C++ TBrowser, as you can see in the attached screenshot:
![broken-tbrowser](https://github.com/root-project/jsroot/assets/14327588/c5ac75d7-833f-4dd4-8022-413781e7f9b5)

I am attaching also `good_qo.root`, which is generated by the same piece of code, the same software version, but can be inspected without problems in JSROOT.
I do not quite understand what is different between the two objects which makes it work or not in JSROOT. Would you have any idea looking at the error?

cc'ing @graduta, who can provide more details about our GUI which uses JSROOT.

Cheers, Piotr

[objects.tar.gz](https://github.com/root-project/jsroot/files/12483723/objects.tar.gz)

**Comment by linev** [comment]
Yes, I can reproduce the problem.
Will try to find a solution.

**Comment by linev** [comment]
@knopers8 

I found and fix the problem. You can try with dev: https://jsroot.gsi.de/dev/

Question - which JSROOT version you are using?
Do you need bug-fix release?

**Comment by knopers8** [comment]
Thank you @linev ! I will let @graduta coordinate with you the bugfix release, but we could certainly use it.

**Comment by linev** [comment]
Are you using 7.4.2 or some other branches?

**Comment by linev** [comment]
Ok, I will do today or tomorrow

**Comment by linev** [comment]
Fixed in https://github.com/root-project/jsroot/releases/tag/7.4.3
