### ISSUE TITLE
Why doesn't this project include a `package-lock.json` file?

### ISSUE THREAD

**Issue by jordan-gillard** [root-project/jsroot#264]
Hey folks, just curious as to why this project doesn't include a `package-lock.json`. Is this intentional? The lock file provides numerous benefits, like guaranteeing package versions on different machines and allowing Node to skip metadata lookup for each package when running `npm ci`.

If this is an accident, I'd be happy to have my first PR to this repo be adding the lock file 😉

**Comment by linev** [comment]
As I can see, `package-lock.json` has some pros and cons.

From one side, it let reproduce exact developer environment.
From other - it strictly fixes all packages versions. 

For me main concern is `gl` package.
It involves compilation of c++ code and this fails very often with newer c++ compilers.
And only after next bugfix `gl` release such compilation problems getting resolved.

Do I understand correctly that `npm install --package-lock=false` will ignore it?
If yes - then I can add `package-lock.json` to repository.

**Comment by jordan-gillard** [comment]
Ahh I see. Maybe I can propose a way to include a `package-lock` file _and_ help with those compiler issues.

What's really nice about a `package-lock` file is exactly what you said about pinning exact package versions. This ensures build consistency and avoids the "well it works-on-my-machine" problem. It helps with debugging issues too. 

I guess it comes down to a tradeoff. If you're regularly updating `gl` to fix compilation issues then you'd have to decide between the stability & reproducibility of adding a `package-lock.json` file, and the ability to update `gl` whenever you want. You are correct that `npm install --package-lock=false` will ignore the `package-lock.json` file and download the latest versions of packages specified in `package.json` (still subject to the semver ranges for each package in `package.json` tho).

Here's what I'd like to propose, since I really dig this project and want to contribute. I have a lot of experience with CI/CD. What if I set up a CI/CD pipeline to run a build matrix on every PR/commit? The CI could build the repo against various C++ compilers to ensure there are no regressions and the project stays in a buildable state.

GitHub actions has the ability to do [matrix builds](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#using-a-matrix-strategy). We could use this to build the project using multiple C++ compiler versions both with and without the `package-lock.json` file. Plus, GitHub actions is free for open source projects (tho I don't know the limits of it, but I'm confident that for this use case it'll be fine). The transparency of the projects build status gives a sense of reliability about the projects health to future users too.

The downside to this approach is that CI/CD adds an ongoing maintenance task. It's **very** straightforward (especially compared to other CI/CD tools, like Jenkins), but it's important to be aware of it.

**Comment by linev** [comment]
Ok. I add `package-lock.json` to repository.

And it would be grate if you can help to integrate CI to JSROOT!

I have independent project for JSROOT testing - https://github.com/linev/jsroot-test
There I testing image production for ROOT classes. 
And recently I add interactive features testing.
Probably it can be used for CI as well.

**Comment by jordan-gillard** [comment]
Awesome! Okay, I look forward to contributing! 😎 We'll be in touch

**Comment by jordan-gillard** [comment]
@linev Progress:
![image](https://github.com/root-project/jsroot/assets/20758755/9839617a-99d4-436c-93b2-c7bd697cb1dc)

**Comment by jordan-gillard** [comment]
Maybe there's a better place to communicate this than here in this issue. Check out [the results of building with different g++ compilers and Node 18 & 20](https://github.com/jordan-gillard/jsroot/actions/runs/6287259943/job/17071563793?pr=1).

We can see that on Ubuntu, the project builds just fine using Node 18 with g++ 9 and later, but fails with all compilers when using Node 20. 

We also see that Node 18 and 20 work with the default MacOS and Windows compilers. [MacOS results](https://github.com/jordan-gillard/jsroot/actions/runs/6287259947), [Windows results](https://github.com/jordan-gillard/jsroot/actions/runs/6287259944).

Because of this, I think we should add the CI tests for MacOS and Windows. For Ubuntu, we should add the tests for Node 18 and g++ 9 and later (it goes to the latest version, which is g++ 13).

Then, in the root-level README.md file we can add that this project officially supports Node 18 and those various compilers. We could state that Node 20 is experimental until `gl` fixes their node-gyp Debian OS bugs.

**Comment by linev** [comment]
Yes, I know about `gl` installation problems.
In some cases it has problem to use latest gcc compiler.
On my latest OpenSUSE I using following command:
```
CXX=g++-12 npm install gl
```
Means I use older C++ compiler to install it.
Can such command be integrated into CI for Ubuntu?

**Comment by jordan-gillard** [comment]
> Can such command be integrated into CI for Ubuntu?

@linev That's what I introduce in the PR I opened yesterday https://github.com/root-project/jsroot/pull/266

Maybe you can give it a review when you have the chance? The CI stages I added in that PR pass if the stage can successfully install all dependencies (including `gl`) and then successfully run the `build` script.

This will keep the project from potential future regressions where something might change which breaks the ability to install `gl` with 1+ versions of the compiler. So, by adding the CI introduced in my PR, you can definitively show which versions of the `gl` compiler are compatible.
