### ISSUE TITLE
Feature request: remove full screen in Escape key press additional to double click

### ISSUE THREAD

**Issue by mrceyhun** [root-project/jsroot#265]
Double click[1] to canvas make it full screen (`jsroot_enlarge_div`) and another double-click removes it. Is it possible to remove full screen (`jsroot_enlarge_div`) on Escape key press. It would really help to UX, cause my first trial was that :)

[1] https://github.com/root-project/jsroot/blob/f111cca0284fab0057ad67e53ea49e4641580187/modules/gpad/TFramePainter.mjs#L1149

**Comment by linev** [comment]
I add `Escape` handling into jsroot dev branch.
You can test it here:

https://jsroot.gsi.de/dev/examples.htm#tcanvas_big

Works only when any frame drawing exists - while key handler implemented only for the frames.

Appears soon in released 7.5 version of JSROOT.

**Comment by mrceyhun** [comment]
It works, many thanks @linev , that's so fast!
