### ISSUE TITLE
Unable to plot root object from browser but it works via NodeJS 

### ISSUE THREAD

**Issue by graduta** [root-project/jsroot#269]
Hi,

I am trying to understand an issue we have with plotting ROOT objects in ALICE via the JSROOT GUI. 

Currently, we are using JSROOT from 2 sources:
- via the ALICE Quality Control GUI which uses a NodeJS backend to read ROOT files and parse them in a JSON format which are then passed to the client side and with the help of the `draw` function, they are plotted.
- we use JSROOT GUI to look at plots individually from JSROOT official GUI. https://jsroot.gsi.de/7.4.3/ 

We have encountered some ROOT files which work fine with the first option (parsing on NodeJS) but we are unable to plot them via the JSROOT GUI. 
I have tried loading the objects in both JSROOT v6 and v7 from https://jsroot.gsi.de/7.4.3/ and https://jsroot.gsi.de/6.3.4/ but I am unable to plot the object. 

I am attaching to this issue the archive containing:
- ROOT file
- screenshot of JSROOT GUI which does not plot the object. (I have tested on both Firefox and Chrome)
- screenshot from QualityControl GUI which plots the object.

Could you point us to where the mistake is done and how we can get the object plotted with JSROOT GUI as well? 

[Archive.zip](https://github.com/root-project/jsroot/files/12782870/Archive.zip)

Thank you,
George

**Comment by linev** [comment]
Object in the ROOT file is not directly supported by JSROOT.

But it is derived from TH2D class.
When you are using ROOT from Node.js - most probably you first cast this object to `TH2D` and only then converted into JSON. Therefore on the client side such object it seen as normal ROOT histogram.

If files reading directly by JSROOT - object type is not recognized as histogram.

But this I can fix fast. I will enable treating of all derived classes as histograms.

**Comment by graduta** [comment]
Thank you for the quick investigation and solution proposed!

**Comment by linev** [comment]
I add support for derived from histograms classes.
It is now in `dev` version https://jsroot.gsi.de/dev/
Will be released soon as `7.5.0`

**Comment by linev** [comment]
Feature released in version 7.5.0
