### ISSUE TITLE
Strage font in firefox

### ISSUE THREAD

**Issue by mvala** [root-project/jsroot#271]
I upgraded fedora to 39 and jsroot font looks nice but it is not same as before. I am probably missing some font. Can you give me hint what font should be installed?

![image](https://github.com/root-project/jsroot/assets/65018/b352aa26-9626-424f-aa17-7d800daed706)

**Comment by linev** [comment]
JSROOT does not use custom fonts. 
By default "Arial" font is used in stats/title/axes labels.

**Comment by mvala** [comment]
I downloaded arial font from https://www.freebestfonts.com/arial-font  and installed it with gnome font manager or store file to `~/.local/share/fonts/arial.ttf` and run `fc-cache -f -v`.

And everything is fine now.
