### ISSUE TITLE
Best way to draw legend in THStack object

### ISSUE THREAD

**Issue by mvala** [root-project/jsroot#275]
Lets assume i have `THStack` object (`VoightPol2_mass`) in file located at https://eos.ndmspc.io/eos/ndmspc/scratch/proj_yx.root. I wold like to draw it with "nostack" option, but i also want to build legend. What is the  best way to draw such object with legend in jsroot?

Thanks

**Comment by linev** [comment]
Hi

Building of legend is functionality of the pad and you can build legend using context menu.
There is no correspondent draw option - neither in canvas not in THStack.
Probably I can add one.

That you can do - write small JavaScript code:
```
const obj = getObjectFromSomewhere();
draw(divid, obj, 'nostack').then(painter => painter.getPadPainter().buildLegend());
```

For the moment THStack object appears in the list of primitive, I add fix to dev branch.

**Comment by mvala** [comment]
Thanks, this is working. Is there a way add position option? Like https://root.cern.ch/doc/master/classTPad.html#a6eebfec5f3dbdb3cd656b26114db28fb

**Comment by linev** [comment]
> Is there a way add position option? 

I need to implement one.

**Comment by linev** [comment]
I add position args to `buildLegend` method.

https://github.com/root-project/jsroot/commit/ec0b922f8ee51e1b49a6f216b1f374d91bac596b

**Comment by mvala** [comment]
Also root is removing part at the beginning.
![Screenshot from 2023-11-06 09-26-19](https://github.com/root-project/jsroot/assets/65018/924df20c-e253-4ecd-b8f4-4cb9368cff20)


and Jsroot

![Screenshot from 2023-11-06 09-25-41](https://github.com/root-project/jsroot/assets/65018/ebc5c7a3-41de-4bbb-909b-f95a92ba8ed4)

**Comment by mvala** [comment]
Or it migt by just default opt is different?

**Comment by linev** [comment]
As I said - current JSROOT adds `THStack` to legend, I just fix this feature today. 
You can try http://jsroot.gsi.de/dev/ now -  I just update it.

**Comment by linev** [comment]
This is that I see:

https://jsroot.gsi.de/dev/?file=https://eos.ndmspc.io/eos/ndmspc/scratch/proj_yx.root&item=VoightPol2_mass+$legend&opt=nostack

Here there is magic name `$legend` used in JSROOT `HierarchyPainter`. It just call `canvas_painter.buildLegend()`

**Comment by mvala** [comment]
Thanks

**Comment by linev** [comment]
Improved functionality included now in https://github.com/root-project/jsroot/releases/tag/7.6.0
