### ISSUE TITLE
React integration

### ISSUE THREAD

**Issue by don4get** [root-project/jsroot#281]
Hello, 

I am quite new using this framework.
I did not find any documentation regarding the integration of jsroot with react, and the examples i found on the net have been deleted.

I also have another question, is jsroot compatible with typescript?

Thank you!

**Comment by linev** [comment]
Hi,

> is jsroot compatible with typescript?

jsroot written with ES6 JavaScript and is not aware about TypeScript.
There is minimal modules declarations in https://github.com/root-project/jsroot/blob/master/types.d.ts - but that's it.

> I did not find any documentation regarding the integration of jsroot with react

I am also not aware about jsroot usage in react. Never tried myself.

> the examples i found on the net have been deleted.

I guess you are speaking about issue #165 
At that time jsroot was plain vanilla JavaScript and was not compatible with webpack.
Now it is possible to create different builds - see:

https://github.com/root-project/jsroot/blob/master/build/rollup.config.js

Only main JSROOT build included into repository, 
but you can generate them with `npm run build` command.

Probably I can add one if you need it.

**Comment by don4get** [comment]
Thank you sergey, 

i just used it directly in react with npm and it works fine for now.
Only small issue remains the fact that I have warnings regarding it s ES6 javascript, and minimal module declarations are not enough for typescript. I just allowed JS in my project and it works.

Bye.
