### ISSUE TITLE
`TGaxis` with function is not properly drawn

### ISSUE THREAD

**Issue by AlbertoPdRF** [root-project/jsroot#282]
I'm trying to add a secondary axis to one of my figures. This secondary axis is a non-linear transformation of the main one. After quite a bit of work, I got it working with:

```cpp
#include "TCanvas.h"
#include "TF1.h"
#include "TGaxis.h"
#include "TH1.h"
#include "TROOT.h"
#include "TStyle.h"

void tgaxis() {
  gROOT->SetStyle("ATLAS");
  gStyle->SetOptStat(0);

  const auto c = new TCanvas();
  const auto min = 42;
  const auto max = 108;
  const auto h = new TH1F("", "", max - min, min, max);
  const auto xa = h->GetXaxis();
  xa->SetTitle("Axis");
  h->Draw();
  c->SetTickx(0);
  c->GetPad(0)->SetTopMargin(0.15375);
  c->Update();

  const auto f = new TF1("f", "(72.289/x)**2", min, max);
  const auto f_min = f->Eval(max);
  const auto f_max = f->Eval(min);
  const auto inv_f = new TF1("inv_f", "72.289/sqrt(x)", f_min, f_max);
  const auto y_max = gPad->GetUymax();
  const auto a = new TGaxis(min, y_max, max, y_max, f_min, f_max, 510, "-");
  a->SetFunction("inv_f");
  a->ImportAxisAttributes(xa);
  a->SetTitle("Secondary axis");
  a->Draw("same");

  c->SaveAs("axis.png");
  c->SaveAs("axis.root");
}
```

While this works with the old graphics, the result with JSROOT is not the expected one, as can be seen in the images below.

Old graphics (correct result):

![Old graphics](https://github.com/root-project/jsroot/assets/26309166/49c89ce6-d6f9-4e93-926e-82e7da59b6ba)

New graphics (incorrect result):

![New graphics](https://github.com/root-project/jsroot/assets/26309166/6ba3322c-e920-4c20-b69a-00d590e37e70)

**Comment by linev** [comment]
Hi,

It is very special usecase.
Function "inv_f" is not stored with `TGaxis` and therefore cannot be used on JSROOT side.

The only I can do is try to support such example in TWebCanvas, where custom I/O rules can be applied.

**Comment by AlbertoPdRF** [comment]
Thanks for the explanation! Wouldn't it make sense to modify `TGaxis` so the function is saved though? It seems like something necessary.

**Comment by linev** [comment]
It will be difficult to change TGaxis class - such change will have strong side effects with I/O.

Let keep issue open - may be later I will provide some workaround in JSROOT.

**Comment by linev** [comment]
I add support of function loading from the file. But function must be stored together with canvas.
Code should look like:
```
  TFile::Open("gaxis.root", "recreate");
  c->Write("c");
  inv_f->Write("inv_f");
  delete gFile;
```

It is part of dev branch: https://jsroot.gsi.de/dev/examples.htm?more#misc_gaxis_func

Relatively soon it will be release as 7.6.0 version

**Comment by linev** [comment]
This works:

http://localhost:8000/jsroot/?file=https://jsroot.gsi.de/files/gaxis_func.root&item=c;1

**Comment by AlbertoPdRF** [comment]
Ok, just tested https://jsroot.gsi.de/dev/?file=https://jsroot.gsi.de/files/gaxis_func.root&item=c;1 and it works too. Awesome! 😄
