### ISSUE TITLE
Partial I/O when reading file from HTTP (S3)

### ISSUE THREAD

**Issue by grzanka** [root-project/jsroot#284]
I was thinking of employing JSROOT as "online browser" of some large (>1GB) ntuples. I was planning to store the ntuples under publicly available HTTP address, on S3 storage (with CORS properly configured). The JSROOT could be part of static JS+HTML app served on GitHub pages.

Main aim would be to use "Open with player" option for ntuple. User could type the column names to plot, and possibly define cuts, like on example below:
<img width="1433" alt="Screenshot 2024-02-07 at 14 08 07" src="https://github.com/root-project/jsroot/assets/7374733/82d75ea9-840b-4b96-8d56-fcf24ccf9239">

I was curious how does I/O works when dealing with large ntuples. When I open the ntuple as URL what is being downloaded to my local browser session ? Only the columns which I select or whole file ?

I saw here:
https://github.com/root-project/jsroot/issues/169#issuecomment-427491607
that you mentioned partial file access.

**Comment by linev** [comment]
JSROOT uses partial I/O for reading files from http servers.

When performing TTree draw only data for selected branches read. 
You can see actual HTTP requests in your browser. Just check this example:

https://root.cern/js/latest/?file=../files/hsimple.root&item=ntuple&opt=px

Very last HTTP request is reading baskets of `px` branch. 
This simple example has only 4 baskets.
![partial_request](https://github.com/root-project/jsroot/assets/4936580/afe9f70d-f220-4580-8ca8-e46a393ebe7d)

**Comment by grzanka** [comment]
> JSROOT uses partial I/O for reading files from http servers.

Thanks ! I will test it .

**Comment by linev** [comment]
> Thanks ! I will test it .

Be aware that some servers using http redirection - which sometime makes impossible usage of partial http requests

**Comment by grzanka** [comment]
With correct CORS settings it seems to work nicely with multiple GB files:

https://root.cern/js/latest/?file=https://s3p.cloud.cyfronet.pl/datarawlv2v3/20231204m2/64nA.root&item=channel_0/trc_file_000/segment_000/negative&opt=peak_area*0.07878780161263421:peak_value*0.07878780161263421%3E%3Eh(1000,-200,0,1000,-100,0)

The only piece which is puzzling me is the access to values in branches.
In the example above I've manually pasted 0.07878780161263421 constant.
It is however present in the channel_0/gain_mV leaf and saved as a string. 
Do you know of any method to adjust my plotting formula and get that number directly from ntuple ?

**Comment by linev** [comment]
For the moment JSROOT do not allow to use data from other objects in `TTree::Draw` expression.
For such custom case you probably need to create your own HTML page and write JavaScript code there.

There is example of such code here:

https://root.cern/js/latest/api.htm#ttree_tselector

https://github.com/root-project/jsroot/blob/master/demo/read_tree.htm

**Comment by linev** [comment]
It is also possible directly use `treeDraw()` function of jsroot. 
Here is example for `node.js`:

https://github.com/root-project/jsroot/blob/master/demo/node/tree_draw.js

Same code can be involved from the browser.
It is very easy to add several lines reading data from other objects in the same file.
