### ISSUE TITLE
TGraph scale by constant factor

### ISSUE THREAD

**Issue by grzanka** [root-project/jsroot#294]
I was wondering if there is a way to Scale TGraph Y values by a constant factor. It seems that ROOT TGraph class has a method called Scale:

https://root.cern.ch/doc/master/classTGraph.html#a6d372fb5644143c107692e66dbc7f3f6

That would give me the option to easily "normalize" some plots.

**Comment by linev** [comment]
Most easy way - use `TGraph::Scale` method in ROOT macro and save modified TGraph in ROOT file.

If scaling should be done in JSROOT - one can implement  such method in JavaScript.
Something like:

```
   <script type='module'>
      import { openFile, draw } from 'https://root.cern/js/latest/modules/main.mjs';
      let file = await openFile('files/graph.root');
      let gr = await file.readObject('graph;1');
      for (let n = 0; n < gr.fNpoints; ++n)
         gr.fY[n] = gr.fY[n]*0.1; 
      draw('drawing', gr, 'L');
   </script>
```

**Comment by linev** [comment]
I guess, I can close issue.
