### ISSUE TITLE
How to remove jsroot source_dir message in node.js

### ISSUE THREAD

**Issue by DraTeots** [root-project/jsroot#296]
I am making a tool using jsroot in node.js. Whenver the script is executed I get a message in console: 

```
Set jsroot source_dir to file:///mnt/c/eic/firebird/root2cad/node_modules/jsroot/, 7.5.5 4/03/2024
```

I install jsroot through npm/yarn and import like: 

```
import * as jsroot from "jsroot";
import * as geom  from "jsroot/geom"
```

How to switch off this message? (As the tool has to be quiet if everything is successful and no verbose flag is given )

**Comment by linev** [comment]
For the moment it is not possible.

I will check that can be done once I am back from vacations in mid April

**Comment by DraTeots** [comment]
Have a great vacation! Everything else works except this, so just in case it is not a high priority in any way.

**Comment by linev** [comment]
I remove such output in case of `node.js`. In master and 7.6 branch.
