### ISSUE TITLE
JSROOT v7 does not display properly plot title while JSROOT v6 does

### ISSUE THREAD

**Issue by graduta** [root-project/jsroot#301]
Hi,

I have some root objects that when I use JSROOT `v7` do display them, they are not fully displayed, for example title is not seen. But if I use JSROOT `6.3.4`, it works very well. 

I have added a few screenshots. GH does not allow me to add the ROOT object itself.

Could you please advise if this is an issue with JSROOT or an issue in how the object is generated and if so, what can we do on our side to improve?

Thank you!

<img width="1728" alt="v6" src="https://github.com/root-project/jsroot/assets/9214854/9dcc7c20-3348-4e0d-b365-5a76ea375ec6">
<img width="1728" alt="v7" src="https://github.com/root-project/jsroot/assets/9214854/f237eb90-0bb2-4939-94ec-040fc69804be">

**Comment by graduta** [comment]
ROOT file 
[TObject_1713530809316.root.txt](https://github.com/root-project/jsroot/files/15041136/TObject_1713530809316.root.txt)

**Comment by linev** [comment]
Actually, it is the way how ROOT works.
I plot same canvas with ROOT graphics - title of the axis histogram skipped. See:

![issue301](https://github.com/root-project/jsroot/assets/4936580/92b6b4b8-b3cb-445a-8fef-b69648711ab5)

Actually - grid lines also should not be - this I will fix too.

**Comment by graduta** [comment]
Hi @linev , thank you for the feedback. What would you recommend to use in order to display the title currently set?

**Comment by linev** [comment]
Just draw histogram with normal option - do not use 'AXIS'. 
If there is no histogram content - it will not be displayed

**Comment by graduta** [comment]
Thank you for the hint. Our users will take care of it going further.
From my point of view, this question can be closed
