### ISSUE TITLE
Enable grid for all items via URL

### ISSUE THREAD

**Issue by grzanka** [root-project/jsroot#302]
I am trying to enable gridxy for all items using URL options.

This URL gives me grid lines for one item
https://jsroot.gsi.de/dev/?file=https://s3.cloud.cyfronet.pl/datarawlv2v4/ic.root&item=%222023-12-04/12_14_27/E8;1%22&opt=gridxy 

![image](https://github.com/root-project/jsroot/assets/7374733/ca82f2f5-f0b7-48b8-b268-0cc62f04e91d)

If I now select another item in the same browser session, the gridlines are gone:
![image](https://github.com/root-project/jsroot/assets/7374733/ac5aff0c-fa51-44bc-9c5b-b07f39df02ac)

I was trying as well https://jsroot.gsi.de/dev/?file=https://s3.cloud.cyfronet.pl/datarawlv2v4/ic.root&opt=gridxy but without success
![image](https://github.com/root-project/jsroot/assets/7374733/b7a0b099-4cef-4efa-85e7-09a3a999005c)

**Comment by grzanka** [comment]
I will then check if I could generate TCanvas with TGraph in ROOT file with grid lines enabled.

**Comment by linev** [comment]
Yes, for `TCanvas` one have to enable grid when it is created.
Or as alternative - provide "gridx" or "gridy" draw options in URL.
