### ISSUE TITLE
WARNING: Multiple instances of Three.js being imported

### ISSUE THREAD

**Issue by EdwardMoyse** [root-project/jsroot#309]
Hi, 

Our project, [phoenix](https://github.com/HSF/phoenix), uses `jsroot`.

However we see this warning:
```
WARNING: Multiple instances of Three.js being imported
```

I assume this is because ROOT is bundling three:
https://github.com/root-project/jsroot/blob/master/libs/three/Three_jsroot.js

Apparently this warning can cause memory leaks and performance issues, so I would like to fix it. However I don't really know what we can do as clients of jsroot? Is there any way `jsroot` could rethink this organisation, and maybe just use e.g. npm?

**Comment by linev** [comment]
Does it mean that you are already loading `three.js` before jsroot?

jsroot use own `three.js` build  - with small patches and reduced number of components.

Can you provide most simple example demonstrating the problem?

**Comment by EdwardMoyse** [comment]
If you unpack the attached directory then do:
```
yarn install
npx vite
```
you will need [yarnpkg](https://yarnpkg.com) and `vite`  (although `http-server` should work too I guess)

Then you should see the warning.

[jsroot-test.zip](https://github.com/root-project/jsroot/files/15309568/jsroot-test.zip)

**Comment by EdwardMoyse** [comment]
(Sorry, forgot to mention that yes, we use a more recent version of three - currently 0.162, but will be 0.165 soon)

See:
https://github.com/HSF/phoenix/blob/main/packages/phoenix-event-display/package.json

**Comment by linev** [comment]
Attached zip file is empty.

But if you are using other three.js - it is just warning.
I even can remove it from version used in jsroot.

jsroot uses ES6 modules which does not expose `three.js` functionality to global scope - except `__THREE__ ` which just holds revision number. 

That kind of memory leaks you have? 
Is it from jsroot? 
Are you tries to cleanup HTML elements?

**Comment by linev** [comment]
In recent jsroot we are using `three,js` revision 162. 
It is last revision which supports WebGL v1.x. 
And seems to be we will be sticked to this version for a while - there is no WebGL v2 support in `node.js` yet.

**Comment by EdwardMoyse** [comment]
[jsroot-test.zip](https://github.com/root-project/jsroot/files/15309893/jsroot-test.zip)

We don't see any issues, except for the WARNING. 

So this comes from `jsroot`? 
https://github.com/root-project/jsroot/blob/21bf59215df01cc02c7011a8c2492001c8cca52f/libs/three/Three_jsroot.js#L206

If so, and if it does not matter, then yes please remove it (or downgrade the severity).

If you google this WARNING (which can also come from `threejs`), the results often indicate that it *can* be a real problem.

**Comment by EdwardMoyse** [comment]
> `And seems to be we will be sticked to this version for a while - there is no WebGL v2 support in node.js yet.

@linev can you point me to any information about this? That would potentially be a problem for us, and it seems too crazy to be true!

**Comment by linev** [comment]
`three.js` remove support of WebGL1 - see https://github.com/mrdoob/three.js/releases/tag/r163, comments about WebGLRenderer .

> If so, and if it does not matter, then yes please remove it (or downgrade the severity).

This is original code from `three.js` - I just comment out there several exports. 

One need to find a way to use external `three.js` with jsroot.

**Comment by EdwardMoyse** [comment]
> `three.js` remove support of WebGL1 - see https://github.com/mrdoob/three.js/releases/tag/r163, comments about WebGLRenderer .

Right, but it was your comment about "there is no WebGL v2 support in node.js yet" which surprised me. Why does node.js even care about WebGL?

> 
> > If so, and if it does not matter, then yes please remove it (or downgrade the severity).
> 
> This is original code from `three.js` - I just comment out there several exports.

Okay, but if it doesn't matter, you could comment out the warning too?

> One need to find a way to use external `three.js` with jsroot.

I completely agree that this is the *real* solution.

**Comment by linev** [comment]
To create any kind of image in node.js out of three.js - one need GL engine. 
In jsroot https://www.npmjs.com/package/gl is used. And it is only supports WebGL1

**Comment by EdwardMoyse** [comment]
Ah, right, so the problem is https://github.com/stackgl/headless-gl. Is [puppeteer](https://pptr.dev) an option? Other people seem to use this together with chromium.

And maybe I'm missing the point, but you're using threejs - can't you use [THREE.WebGLRenderer()](https://threejs.org/docs/index.html?q=WebGLRenderer#api/en/renderers/WebGLRenderer)? This is what we do in Phoenix.

**Comment by linev** [comment]
WebGLRenderer requires GL context. To get it in node.js one uses headless-gl. 

`puppeteer` is just tool to run web browsers. But if one uses web browsers - `node.js` is not really necessary.

**Comment by EdwardMoyse** [comment]
I guess from your edit this is just for CI and not runtime?

If it's just for testing, we use [cypress](https://docs.cypress.io/guides/overview/why-cypress):
https://github.com/HSF/phoenix/tree/main/packages/phoenix-ng/projects/phoenix-app/cypress

Maybe this could be an easier option that using node.js for you as well?

**Comment by linev** [comment]
Yes, `node.js` used for CI - but not only.

One can directly use jsroot from node.js for ROOT data analysis and image production - therefore option to properly produce images for 3d drawings is valuable.

**Comment by linev** [comment]
@EdwardMoyse 

You can try special JSROOT build with supports external `three` module.

Try to checkout repository, then do:
```
npm install
npm build
```

After that in `build/` sub-directory you should get `geom_nothreejs.mjs` file.
It requires `three` and `three/addons` modules to be provided.
Last is additional components from three.js examples. 

Maybe some important for you JSROOT functions are missing - you can try to add them to `modules/geom/bundle.mjs` file and then provide PR

**Comment by DraTeots** [comment]
> Yes, `node.js` used for CI - but not only.
> 
> One can directly use jsroot from node.js for ROOT data analysis and image production - therefore option to properly produce images for 3d drawings is valuable.

Root2cad uses node.js to convert geometries to GLTF

https://github.com/eic/root2cad

**Comment by linev** [comment]
@DraTeots 

Crucial here is support of 3D rendering with `node.js`. 
Without proper `gl` component `three.js` model can not be rendered into PNG or JPEG image.

In your usecase such functionality not used. 

Looks like for some time jsroot will be sticked with `three.js` r162. 

The only I can do now - provide better support of external `three.js`.

**Comment by linev** [comment]
I add example which shows usage of special jsroot build for external three.js:

https://github.com/root-project/jsroot/blob/master/demo/tgeo_build_external_threejs.htm

It will be included into v 7.7.1 which I plan to release today.

**Comment by EdwardMoyse** [comment]
@linev sorry, I keep meaning to come back to this. I did have a look when you first posted, but I couldn't see how this would work for `phoenix` given we use jsroot as a [module](https://github.com/HSF/phoenix/blob/87e9e14f3be5e139263bfae7210f0399a99b466e/packages/phoenix-event-display/package.json#L45) and you are not exposing `geom_nothreejs` as far as I can see...

**Comment by linev** [comment]
>  you are not exposing `geom_nothreejs` as far as I can see...

It is included in npm package and obtained with `npm install jsroot`.
And can be build when running `npm run build`

**Comment by EdwardMoyse** [comment]
Thanks for the reply @linev. I'm really not an expert at this, and so I apologise if I am just not understanding... but in 
https://github.com/root-project/jsroot/blob/master/package.json
you have:
```
  "main": "./build/jsroot.js",
  "module": "./modules/main.mjs",
  "types": "./types.d.ts",
```

And in `types.d.ts` you only `declare module "jsroot";`

So how do I update a line like this in phoenix:
```
import { httpRequest, build, openFile  } from 'jsroot';
```

As far as I can see, I can't just do:
```
import { httpRequest, build, openFile  } from 'jsroot_geom';
```

**Comment by linev** [comment]
While it is not standard build, one need some workaround to use it.

When running from the browser, one can [take this example](https://github.com/root-project/jsroot/blob/master/demo/tgeo_build_external_threejs.htm)

Never tried to use this build in the `node.js`. But something like:

   npm install three 
   npm install jsroot 
   
And then create `test.mjs` file with content:
```
import { httpRequest, version } from './node_modules/jsroot/build/geom_nothreejs.mjs';
console.log('JSROOT version', version)
```

I will provide more convenient import in future JSROOT releases
