### ISSUE TITLE
TGeoPainter build ignores Infinity as numnodes

### ISSUE THREAD

**Issue by DraTeots** [root-project/jsroot#311]
This one works: 

```typescript
    geometry = build(rootGeometry,
      {
        numfaces: Infinity,
        numnodes: 500000000,
        instancing:-1,
        dflt_colors: true,
        vislevel: Infinity,
        doubleside:true,
        transparency:true
      });
```

And this doesn't

```typescript
    geometry = build(rootGeometry,
      {
        numfaces: Infinity,
        numnodes: Infinity,
        instancing:-1,
        dflt_colors: true,
        vislevel: Infinity,
        doubleside:true,
        transparency:true
      });
```

In the later case, it looks like the numnodes gets some default value. I.e. something top level is rendered but not the deeper details. 

I tested numfaces and vislevel seems to treat Infinity correctly

For the reference: 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity

**Comment by linev** [comment]
> In the later case, it looks like the numnodes gets some default value

Yes, if `Infinite` (or invalid) value configured for `numnodes` - it get 10000 as default.
I prefer to keep such limitation - there are branches in algorithm selecting 20% of maximal number of nodes.

You always can try to specify larger number like `1e6` or `1e7` - but not `Infinity`
By such large number of nodes one should try to use `instancing` - otherwise there are will be too much meshes created.

**Comment by DraTeots** [comment]
Could I try advocate that Infinity is not an invalid value and it would be good if treated as "just big number"? 

1. My intent setting Infinity there was "I don't care how much, do all of them" and I believe it is common intent of using Infinity for that `number`. I believe it goes along with the common `intent` of using Infinity in such places. 

2. In typescript Infinity is commonly used as a number placeholder indicating what could be used in C++ as MAX_INT or infinity. It is much harder to track if it is common in vanilla javascript as it is historically less coherent, but in typescript is a common thing. 

3. Infinity works very well in logic, so it is safe to use as a `number`

```
5 > Infinity
false
5 < Infinity
true
-Infinity < Infinity
true
-Infinity == Infinity
false
Infinity == Infinity
true
Infinity > Infinity
false
Infinity >= Infinity
true
```

It certainly have some artificial mathematics such as 

```
Infinity * 0
NaN
```

But I thought numnodes is used as some sort of upper boundaries and Infinity is safe there. 


4.  Putting like 1e6 or 1e7 is a legitimate practice but it instantly starts a guessing game "is it enough?". E.g. You suggested 1e6 but that would be less than EIC geometry number of nodes (which is ~5.5e6). I know it now, but I didn't know it 2 months ago. At that time I would say it is 2 orders of magnitude less and 1e6 is definitely enough which is wrong. Now if I were absolutely new to trhee.js and jsroot, which one could anticiapte e.g. from student, I could be completely stuck with why something is not rendered. It would be easier if Infinity just worked

5. Would be good to have some kind of warning in console maybe that "numnodes value was incorrect! Set numnodes to default 10k" 

P.S. This is all kind of opinionated but I share from my experience point, so maybe you could consider.

**Comment by linev** [comment]
As I mention - because of internal functionality `Infinity` is not value which can be used directly in the code.
But I significantly increase default value which is assigned when `Infinity` is specified as argument.
See https://github.com/root-project/jsroot/commit/f7162cdbe2c145905e664da78e37d23ec481427f

**Comment by DraTeots** [comment]
Thank you!!!
