### ISSUE TITLE
Inconsistent content between github sourca and tarballs on jsroot.gsi.de

### ISSUE THREAD

**Issue by ellert** [root-project/jsroot#312]
In the github repo, the files

modules/draw/TASImage.mjs
modules/hierarchy.mjs

no longer exist. They where renamed to

modules/draw/TASImagePainter.mjs
modules/gui/HierarchyPainter.mjs

respectively. But in the tarballs published on jsroot.gsi.de, e.g.
https://jsroot.gsi.de/7.7.1/JsRoot771.tar.gz
The old files are still present.

**Comment by linev** [comment]
Yes, files were remaining in JSROOT build directories.
They will not appear in next releases.

Thanks for reporting the problem.
