### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by Dqixol** [root-project/jsroot#315]
Dear Developers,

Thanks very much for the amazing work bringing root to the browser and Jupyter notebook.

I recently tried to use the jsroot website instead of a local root browser. 

I would appreciate if you could make the website a PWA, so that people can have a separate window for it instead of a tab in the browser.

Please let me know if you think this is a good idea.

Cheers, Qichen

**Comment by linev** [comment]
Dear Qichen,

Can you describe in more details which functionality you are missing?

**Comment by linev** [comment]
Closing issue.

@Dqixol you can reopen it if provide more info that exactly you want to have from JSROOT
