### ISSUE TITLE
bug: TProfile2D bins with entries but value 0 not being shown in COL draw option

### ISSUE THREAD

**Issue by will-cern** [root-project/jsroot#316]
Hello,

I've noticed that JSROOT doesn't display the bins that have entries in a TProfile2D but where the value/content of the bin is 0. 
Here's a reproducer:
```
%jsroot on
p = ROOT.TProfile2D("p","p",10,0,10,10,0,10)
p.Fill(4,4,0)
p.Draw("COLZ")
ROOT.gPad.GetCanvas().Draw()
```
That filled bin should show up. It does with jsroot is turned off.

**Comment by linev** [comment]
Now empty TProfile2D bins with non-zero entries will be shown in color draw
