### ISSUE TITLE
Histogram stat box for "Entries" showing Integral instead Entries 

### ISSUE THREAD

**Issue by msabbott21** [root-project/jsroot#320]
First, thank you so much for this extension, I use it nearly every day!!!

Bug report:
JSROOT version 7.7.4 
el9_amd64_gcc12

I have some histograms that are filled with weights. For histograms that are filled only one time (see example attached), the stats box prints the Integral rather than the Entries. In this case, the stat box should show "Entries 1" instead of "Entries 0.001190820".

When calling hist.GetEntries() in pyroot, it correctly returns "1.0".
When printing the contents of the histogram directly using the terminal, it also correctly shows that Entries=1.
When creating a canvas with a statbox and saving that directly to a png, it also correctly shows that Entries=1. 
So ROOT definitely considers Entries to be 1. This issue seems to stem from the JSROOT extension.

Example of incorrect statbox:
![image](https://github.com/user-attachments/assets/f5065f6a-c695-4d3b-a742-242e667f3a57)

Let me know if there is any more information I can provide.

**Comment by linev** [comment]
Thanks for reporting the problem.
For that ever reasons `entries == 1` was handled wrong. 
I will provide fix

**Comment by linev** [comment]
I apply fix to master and 7.7 branch. Soon will be released with 7.7.5

**Comment by msabbott21** [comment]
thanks a bunch!

**Comment by linev** [comment]
Fix published in https://github.com/root-project/jsroot/releases/tag/7.7.5
